#!/usr/bin/env python3
"""Build county HHW hubs for the 50 largest metros.

One hub per unique county/regional program. Long Beach shares LA County;
Arlington shares Tarrant with Fort Worth. Official city HHW sources stay
on city dispose pages. Distinct suburban programs use the county URL we
verified. Do not invent fees or claim a depot that does not exist.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TODAY = "2026-08-13"

# city_slug -> hub facts. kind:
#   county_program — official source already is the county/regional program
#   county_distinct — suburbs use a different official program than the city
#   consolidated — city and county are the same government
#   no_county_depot — county does not run a general HHW depot
#   city_anchor — we verified the city program; county eligibility is not automatic
ROWS: list[dict] = [
    {
        "county": "New York City",
        "county_slug": "new-york-city",
        "state": "NY",
        "state_slug": "new-york",
        "cities": ["new-york"],
        "kind": "consolidated",
        "program_name": "DSNY Special Waste / SAFE",
        "who_qualifies": "Residents of the five boroughs. Nassau, Westchester, and New Jersey counties are different programs.",
        "city_note": "There is no separate NYC county HHW. The city program is the program.",
        "access": "Special Waste Drop-Off sites and SAFE events — residency rules on the DSNY page.",
    },
    {
        "county": "Los Angeles County",
        "county_slug": "los-angeles",
        "state": "CA",
        "state_slug": "california",
        "cities": ["los-angeles", "long-beach"],
        "kind": "county_distinct",
        "program_name": "LA County Public Works CleanLA HHW / E-waste",
        "source_name": "LA County Public Works — CleanLA Household Hazardous Waste",
        "source_url": "https://cleanla.lacounty.gov/hhw/",
        "who_qualifies": "Los Angeles County residents. City of Los Angeles also has S.A.F.E. Centers; Long Beach has its own HHW page.",
        "city_note": "City of Los Angeles S.A.F.E. Centers are not the county weekend-event / permanent-center program. Confirm which site your address may use.",
        "facility": "County events plus permanent centers (including EDCO Signal Hill and Antelope Valley). Confirm the current calendar on CleanLA.",
        "access": "Free HHW/e-waste events and listed permanent centers. Do not transport more than the county’s posted limit (commonly 15 gallons / 125 lb).",
        "accepted_hint": "Household chemicals, batteries, paint, and many electronics at county HHW/e-waste events.",
        "not_accepted_hint": "Business waste, explosives, radioactive materials, trash, tires, and white goods (appliances).",
        "fee_note": "County collection events and listed centers are free for residents. Confirm on CleanLA.",
        "last_verified_at": TODAY,
    },
    {
        "county": "Cook County",
        "county_slug": "cook",
        "state": "IL",
        "state_slug": "illinois",
        "cities": ["chicago"],
        "kind": "no_county_depot",
        "program_name": "Cook County Environment and Sustainability — suburban HHW",
        "source_name": "Cook County — Environment and Sustainability",
        "source_url": "https://www.cookcountyil.gov/agency/environment-and-sustainability",
        "who_qualifies": "Suburban Cook is not Chicago. Chicago residents use HCCRF. Suburbs use municipal programs or regional sites the county lists.",
        "city_note": "Chicago HCCRF (1150 N. Branch) is a city facility. It is not a substitute county depot for every suburb.",
        "facility": "No single countywide depot we can treat as open. The county has pointed residents at Chicago HCCRF, Naperville, and other Illinois sites while a South Holland facility was planned.",
        "access": "Confirm current suburban drop-off on the Cook County environment page before you haul. Do not assume the South Holland project is open.",
        "accepted_hint": "Typical HHW (paint, solvents, batteries, auto fluids) at whatever site your suburb actually uses.",
        "not_accepted_hint": "Do not treat a city-only site as countywide without checking residency.",
        "fee_note": "Fees and hours belong to the site you use. Confirm on that official page.",
        "last_verified_at": TODAY,
    },
    {
        "county": "Harris County",
        "county_slug": "harris",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["houston"],
        "kind": "county_distinct",
        "program_name": "Harris County Household Hazardous Waste Facility",
        "source_name": "Harris County Office of the County Engineer — HHW",
        "source_url": "https://oce.harriscountytx.gov/Services/Household-Hazardous-Waste",
        "who_qualifies": "Harris County residents who live outside incorporated Houston — people who do not receive City of Houston water, trash, or recycling.",
        "city_note": "City of Houston residents use Environmental Service Centers, not the county Hahl Road facility.",
        "facility": "6900 Hahl Road, Houston, TX 77040 (290 and Gessner).",
        "access": "Appointment only. Tue/Wed 9 a.m.–3 p.m.; 2nd and 4th Saturdays 9 a.m.–2 p.m. Precinct HazMobile events in spring and fall.",
        "accepted_hint": "Household chemicals, paint, batteries, aerosols, small propane, mercury items, limited tires. Household use only.",
        "not_accepted_hint": "TVs and computers, sharps, smoke detectors, explosives, appliances, furniture, trash, and business waste.",
        "fee_note": "No charge for qualifying household waste. Confirm on the county page.",
        "last_verified_at": TODAY,
    },
    {
        "county": "Maricopa County",
        "county_slug": "maricopa",
        "state": "AZ",
        "state_slug": "arizona",
        "cities": ["phoenix"],
        "kind": "no_county_depot",
        "program_name": "Maricopa County solid waste — no general HHW depot",
        "source_name": "Maricopa County — refuse / HHW FAQ",
        "source_url": "https://www.maricopa.gov/faq.aspx?qid=498",
        "who_qualifies": "Incorporated cities run their own HHW. Unincorporated areas use private service, not a county HHW plant.",
        "city_note": "Phoenix solid-waste customers use the city’s HHW home collection (limits apply). Mesa and other cities have their own sites.",
        "facility": "County transfer stations are not a general HHW depot. They may take a small amount of used oil and antifreeze only.",
        "access": "Use your city’s HHW program or a private hazardous-waste service. Confirm oil/antifreeze limits at a county transfer station before you go.",
        "accepted_hint": "City programs vary. Phoenix is home collection for eligible solid-waste customers.",
        "not_accepted_hint": "Batteries, paint, and mixed HHW are prohibited at county disposal facilities.",
        "fee_note": "Do not assume free county drop-off. Confirm on your city program.",
        "last_verified_at": TODAY,
    },
    {
        "county": "Philadelphia County",
        "county_slug": "philadelphia",
        "state": "PA",
        "state_slug": "pennsylvania",
        "cities": ["philadelphia"],
        "kind": "consolidated",
        "program_name": "City of Philadelphia Sanitation Convenience Centers / HHW events",
        "who_qualifies": "Philadelphia residents. Suburban counties (Montgomery, Bucks, Delaware, Camden) are different programs.",
        "city_note": "The city and the county are the same government. This hub is the city HHW/SCC path, not a second county plant.",
        "access": "Convenience centers and posted HHW events. Confirm liquids vs dried latex on the city page.",
    },
    {
        "county": "Bexar County",
        "county_slug": "bexar",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["san-antonio"],
        "kind": "city_anchor",
        "program_name": "City of San Antonio Household Hazardous Waste",
        "who_qualifies": "The program we verified is City of San Antonio HHW (CPS bill + ID). Unincorporated Bexar and other cities must confirm eligibility.",
        "city_note": "Do not assume a suburban Bexar address can use 7030 Culebra. Check the official SA HHW page.",
        "access": "City HHW drop-off with posted limits. Confirm hours and ID on sa.gov.",
    },
    {
        "county": "San Diego County",
        "county_slug": "san-diego",
        "state": "CA",
        "state_slug": "california",
        "cities": ["san-diego"],
        "kind": "city_anchor",
        "program_name": "City of San Diego Household Hazardous Waste Transfer Facility",
        "who_qualifies": "The program we verified is the City of San Diego Miramar HHW facility. Other county cities and unincorporated areas use different sites.",
        "city_note": "Miramar HHW is a city Environmental Services site. It is not automatically the countywide depot.",
        "access": "City HHW transfer facility — confirm residency and hours on the city page.",
    },
    {
        "county": "Dallas County",
        "county_slug": "dallas",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["dallas"],
        "kind": "county_program",
        "program_name": "Dallas County Home Chemical Collection Center",
        "who_qualifies": "Dallas residents use the Home Chemical Collection Center we verified. Other Dallas County cities should confirm they are listed.",
        "city_note": "The city sanitation page points at a county chemical-collection site — that is the suburban-style program for this metro.",
        "access": "Home Chemical Collection Center — confirm hours and residency on the Dallas sanitation page.",
    },
    {
        "county": "Santa Clara County",
        "county_slug": "santa-clara",
        "state": "CA",
        "state_slug": "california",
        "cities": ["san-jose"],
        "kind": "county_program",
        "program_name": "County of Santa Clara Household Hazardous Waste",
        "who_qualifies": "Santa Clara County residents, including San Jose, with an appointment on the county HHW site.",
        "city_note": "San Jose does not run a separate city HHW plant. The county program is the program.",
        "access": "County HHW drop-off by appointment. Confirm on hhw.santaclaracounty.gov.",
    },
    {
        "county": "Travis County",
        "county_slug": "travis",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["austin"],
        "kind": "city_anchor",
        "program_name": "Austin Resource Recovery on-demand HHW / Recycle & Reuse Center",
        "who_qualifies": "The program we verified is Austin Resource Recovery. Other Travis County cities and unincorporated areas must confirm their own HHW.",
        "city_note": "On-demand HHW and the Recycle & Reuse Center are city services, not a countywide depot.",
        "access": "On-demand pickup (posted gallon/year caps) or RRC appointment. Confirm on austintexas.gov.",
    },
    {
        "county": "Duval County",
        "county_slug": "duval",
        "state": "FL",
        "state_slug": "florida",
        "cities": ["jacksonville"],
        "kind": "consolidated",
        "program_name": "City of Jacksonville Household Hazardous Waste Facility",
        "who_qualifies": "Jacksonville / Duval consolidated-government residents. Nearby counties (Clay, St. Johns) are different programs.",
        "city_note": "The city and most of the county are the same government. The HHW facility is the metro program.",
        "access": "HHW Facility — never curbside. Confirm gallon limits on jacksonville.gov.",
    },
    {
        "county": "Tarrant County",
        "county_slug": "tarrant",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["fort-worth", "arlington"],
        "kind": "county_program",
        "program_name": "Fort Worth Environmental Collection Center / Drop-Off Station HHW",
        "who_qualifies": "Fort Worth residents use ECC / drop-off stations. Arlington’s verified path is the Fort Worth ECC — confirm current Arlington eligibility.",
        "city_note": "This is the Tarrant-side chemical drop-off we verified. It is not Dallas County’s Home Chemical Collection Center.",
        "access": "ECC and drop-off station HHW with posted gallon caps. Confirm on Fort Worth Environmental Services.",
    },
    {
        "county": "Franklin County",
        "county_slug": "franklin",
        "state": "OH",
        "state_slug": "ohio",
        "cities": ["columbus"],
        "kind": "county_program",
        "program_name": "SWACO Household Hazardous Waste Facility",
        "who_qualifies": "The Columbus page we verified sends HHW to SWACO (Solid Waste Authority of Central Ohio). Confirm your Franklin County city is eligible.",
        "city_note": "This is a regional authority, not a Columbus-only closet. City bulky rules are a different channel.",
        "access": "SWACO HHW — 645 E 8th Ave. Confirm current hours on the Columbus / SWACO pages.",
    },
    {
        "county": "Marion County",
        "county_slug": "marion",
        "state": "IN",
        "state_slug": "indiana",
        "cities": ["indianapolis"],
        "kind": "county_program",
        "program_name": "Marion County ToxDrop",
        "who_qualifies": "Marion County / Indianapolis residents at posted Saturday ToxDrop sites.",
        "city_note": "ToxDrop is the county hazardous-waste drop-off, not a city bulky day.",
        "access": "Saturday drop-offs with posted weight/gallon caps. Confirm sites on indy.gov.",
    },
    {
        "county": "Mecklenburg County",
        "county_slug": "mecklenburg",
        "state": "NC",
        "state_slug": "north-carolina",
        "cities": ["charlotte"],
        "kind": "county_program",
        "program_name": "Mecklenburg County Solid Waste / Wipe Out Waste",
        "who_qualifies": "Mecklenburg County residents, including Charlotte, at full-service recycling centers that take HHW.",
        "city_note": "Charlotte’s verified HHW path is the county solid-waste program.",
        "access": "County full-service recycling center HHW. Confirm on wipeoutwaste.mecknc.gov.",
    },
    {
        "county": "San Francisco City and County",
        "county_slug": "san-francisco",
        "state": "CA",
        "state_slug": "california",
        "cities": ["san-francisco"],
        "kind": "consolidated",
        "program_name": "Recology San Francisco Household Hazardous Waste Facility",
        "who_qualifies": "San Francisco residents. Daly City, South San Francisco, and San Mateo County are different programs.",
        "city_note": "The city and county are the same government. 501 Tunnel Ave is the city/county HHW facility.",
        "access": "Recology HHW Facility — confirm hours and residency on the Recology SF page.",
    },
    {
        "county": "King County",
        "county_slug": "king",
        "state": "WA",
        "state_slug": "washington",
        "cities": ["seattle"],
        "kind": "county_program",
        "program_name": "Seattle / King County household hazardous waste facilities",
        "who_qualifies": "The Seattle page we verified is for King County residents at the North and South Seattle HHW facilities.",
        "city_note": "This is the county hazardous-waste program hosted at Seattle facilities — not Seattle bulky pickup.",
        "access": "North/South Seattle HHW facilities. Confirm hours on Seattle Public Utilities.",
    },
    {
        "county": "Denver City and County",
        "county_slug": "denver",
        "state": "CO",
        "state_slug": "colorado",
        "cities": ["denver"],
        "kind": "consolidated",
        "program_name": "City and County of Denver Household Hazardous Waste",
        "who_qualifies": "Denver residents. Aurora, Lakewood, and other metro cities are different programs.",
        "city_note": "Denver is a consolidated city-county. Aurora has its own paint/chemicals page.",
        "access": "HHW At-Your-Door and posted paint/battery drop-off. Confirm copays and limits on denvergov.org.",
    },
    {
        "county": "District of Columbia",
        "county_slug": "district",
        "state": "DC",
        "state_slug": "district-of-columbia",
        "cities": ["washington"],
        "kind": "consolidated",
        "program_name": "DC DPW Special Waste Collection Events",
        "who_qualifies": "District residents. Montgomery, Prince George’s, Arlington, and Fairfax are different programs.",
        "city_note": "There is no permanent DC HHW depot in the program we verified — events only.",
        "access": "Special Waste Events (including RFK Lot 8). No permanent depot. Confirm the calendar on dpw.dc.gov.",
    },
    {
        "county": "Davidson County",
        "county_slug": "davidson",
        "state": "TN",
        "state_slug": "tennessee",
        "cities": ["nashville"],
        "kind": "consolidated",
        "program_name": "Metro Nashville Household Hazardous Waste",
        "who_qualifies": "Metro Nashville / Davidson County residents. Surrounding counties are different programs.",
        "city_note": "Metro is the city-county. Latex/acrylic is often trash after it is fully dry — not HHW.",
        "access": "Metro HHW / convenience-center rules. Confirm what is not accepted on nashville.gov.",
    },
    {
        "county": "Oklahoma County",
        "county_slug": "oklahoma",
        "state": "OK",
        "state_slug": "oklahoma",
        "cities": ["oklahoma-city"],
        "kind": "city_anchor",
        "program_name": "City of Oklahoma City HHW Collection Center",
        "who_qualifies": "The program we verified is the OKC HHW Collection Center with a water bill. Other Oklahoma County cities must confirm eligibility.",
        "city_note": "1621 S. Portland is a city facility, not an automatic countywide depot.",
        "access": "HHW Collection Center — confirm hours and ID on okc.gov.",
    },
    {
        "county": "El Paso County",
        "county_slug": "el-paso",
        "state": "TX",
        "state_slug": "texas",
        "cities": ["el-paso"],
        "kind": "city_anchor",
        "program_name": "City of El Paso Citizen Collection Stations — HHW",
        "who_qualifies": "The program we verified is City of El Paso collection stations (water bill + ID). Other El Paso County towns must confirm.",
        "city_note": "This is not El Paso County, Colorado. Texas El Paso CCS HHW is a city service.",
        "access": "HHW at Citizen Collection Stations. Confirm hours on elpasotexas.gov.",
    },
    {
        "county": "Suffolk County",
        "county_slug": "suffolk",
        "state": "MA",
        "state_slug": "massachusetts",
        "cities": ["boston"],
        "kind": "city_anchor",
        "program_name": "City of Boston Zero Waste Day",
        "who_qualifies": "Boston residents at posted Zero Waste Day events. Other Suffolk County cities (Revere, Chelsea, Winthrop) run their own events.",
        "city_note": "Boston has no permanent HHW depot in the program we verified — events only.",
        "access": "Zero Waste Day with residency proof and posted gallon caps. Confirm the calendar on boston.gov.",
    },
    {
        "county": "Multnomah County",
        "county_slug": "multnomah",
        "state": "OR",
        "state_slug": "oregon",
        "cities": ["portland"],
        "kind": "county_program",
        "program_name": "Oregon Metro household hazardous waste",
        "who_qualifies": "The Portland path we verified is Oregon Metro HHW — a regional program, not a Portland-only closet.",
        "city_note": "Metro covers the Portland metro (including parts of Clackamas and Washington counties). Confirm your address on oregonmetro.gov.",
        "access": "Metro HHW facilities / dried-can rules. Liquid product goes to Metro, not the trash cart.",
    },
    {
        "county": "Clark County",
        "county_slug": "clark",
        "state": "NV",
        "state_slug": "nevada",
        "cities": ["las-vegas"],
        "kind": "county_program",
        "program_name": "Clark County Household Hazardous Waste",
        "who_qualifies": "Clark County residents. Las Vegas city bulky is a different channel.",
        "city_note": "The Las Vegas HHW path we verified is the county rotating-site / HHW program.",
        "access": "County HHW rotating sites. Dried latex is often trash; liquid goes to HHW. Confirm on clarkcountynv.gov.",
    },
    {
        "county": "Wayne County",
        "county_slug": "wayne",
        "state": "MI",
        "state_slug": "michigan",
        "cities": ["detroit"],
        "kind": "city_anchor",
        "program_name": "City of Detroit DPW Household Hazardous Waste",
        "who_qualifies": "The program we verified is Detroit resident HHW at 2000 E. Ferry. Other Wayne County cities have their own drop-offs.",
        "city_note": "Detroit DPW HHW is not a countywide Wayne depot.",
        "access": "DPW HHW Receiving Facility — posted weekday and 4th-Saturday hours. Confirm on detroitmi.gov.",
    },
    {
        "county": "Shelby County",
        "county_slug": "shelby",
        "state": "TN",
        "state_slug": "tennessee",
        "cities": ["memphis"],
        "kind": "county_program",
        "program_name": "Shelby County Household Hazardous Waste",
        "who_qualifies": "Shelby County / Memphis residents at the county HHW program. Latex is often not accepted — dry it for trash.",
        "city_note": "Memphis’s verified HHW path is the county program, not a city bulky day.",
        "access": "County HHW. Confirm what is refused (including latex) on shelbycountytn.gov.",
    },
    {
        "county": "Jefferson County",
        "county_slug": "jefferson",
        "state": "KY",
        "state_slug": "kentucky",
        "cities": ["louisville"],
        "kind": "consolidated",
        "program_name": "Louisville Metro Haz Bin",
        "who_qualifies": "Louisville Metro / Jefferson County residents. Surrounding Kentucky counties are different programs.",
        "city_note": "Metro is the city-county. Latex is often trash after it is fully dry — not Haz Bin.",
        "access": "Haz Bin hazardous-materials drop-off. Confirm what is not accepted on louisvilleky.gov.",
    },
    {
        "county": "Baltimore City",
        "county_slug": "baltimore-city",
        "state": "MD",
        "state_slug": "maryland",
        "cities": ["baltimore"],
        "kind": "consolidated",
        "program_name": "City of Baltimore Household Hazardous Waste",
        "who_qualifies": "Baltimore City residents. Baltimore County is a different government with a different HHW program.",
        "city_note": "This is the independent city, not Baltimore County. Do not haul city waste to a county site without checking.",
        "access": "City HHW / Sisson Street for oil paint. Dried latex is often trash. Confirm on baltimorecity.gov.",
    },
    {
        "county": "Milwaukee County",
        "county_slug": "milwaukee",
        "state": "WI",
        "state_slug": "wisconsin",
        "cities": ["milwaukee"],
        "kind": "county_program",
        "program_name": "MMSD home haz-mat collection",
        "who_qualifies": "The Milwaukee path we verified is Milwaukee Metropolitan Sewerage District HHW — a regional program.",
        "city_note": "MMSD is not City bulky. Medications are not accepted at MMSD HHW.",
        "access": "Lincoln Avenue and 13th Street sites with posted hours. Confirm on mmsd.com.",
    },
    {
        "county": "Bernalillo County",
        "county_slug": "bernalillo",
        "state": "NM",
        "state_slug": "new-mexico",
        "cities": ["albuquerque"],
        "kind": "county_program",
        "program_name": "Albuquerque / Bernalillo Household Hazardous Waste Collection Center",
        "who_qualifies": "The city page we verified lists Albuquerque and Bernalillo County residents at the Girard HHW center.",
        "city_note": "This is the metro HHW center, not a bulky-furniture site.",
        "access": "HHW Collection Center — 2720 Girard Blvd NE. Confirm hours on cabq.gov.",
    },
    {
        "county": "Pima County",
        "county_slug": "pima",
        "state": "AZ",
        "state_slug": "arizona",
        "cities": ["tucson"],
        "kind": "city_anchor",
        "program_name": "City of Tucson Household Hazardous Waste",
        "who_qualifies": "The program we verified is City of Tucson HHW at Los Reales. Other Pima County towns must confirm eligibility.",
        "city_note": "Los Reales Sustainability Campus HHW is a city Environmental Services site.",
        "access": "HHW with posted paint-product caps. Confirm on tucsonaz.gov.",
    },
    {
        "county": "Fresno County",
        "county_slug": "fresno",
        "state": "CA",
        "state_slug": "california",
        "cities": ["fresno"],
        "kind": "county_program",
        "program_name": "Fresno County Environmental Compliance Center / HHW network",
        "who_qualifies": "The Fresno city page we verified sends residential HHW to the county ECC and network sites.",
        "city_note": "City trash rules and county HHW are different channels.",
        "access": "Fresno County ECC and listed network sites. Confirm on the city / county pages.",
    },
    {
        "county": "Sacramento County",
        "county_slug": "sacramento",
        "state": "CA",
        "state_slug": "california",
        "cities": ["sacramento"],
        "kind": "city_anchor",
        "program_name": "City of Sacramento HHW at Sacramento Recycling & Transfer",
        "who_qualifies": "The program we verified is the city HHW site at 8491 Fruitridge. Other Sacramento County cities have their own drop-offs.",
        "city_note": "Unincorporated county and cities such as Elk Grove are not automatically this Fruitridge site.",
        "access": "City HHW facility. Confirm residency on cityofsacramento.gov.",
    },
    {
        "county": "Jackson County",
        "county_slug": "jackson",
        "state": "MO",
        "state_slug": "missouri",
        "cities": ["kansas-city"],
        "kind": "city_anchor",
        "program_name": "KC Water Household Hazardous Waste",
        "who_qualifies": "The program we verified is KC Water HHW for Kansas City, Missouri residents. Kansas-side Johnson County is a different program.",
        "city_note": "KCMO HHW is not a stand-in for every Jackson County suburb, and it is not Kansas.",
        "access": "KC Water Environmental Campus HHW — 4707 Deramus. Confirm hours on kcwater.us.",
    },
    {
        "county": "Fulton County",
        "county_slug": "fulton",
        "state": "GA",
        "state_slug": "georgia",
        "cities": ["atlanta"],
        "kind": "no_county_depot",
        "program_name": "Fulton County / City of Atlanta — no permanent HHW depot",
        "source_name": "Fulton County — pollution prevention / HHW days",
        "source_url": "https://www.fultoncountyga.gov/services/water-services/public-education-and-outreach/pollution-prevention",
        "who_qualifies": "Atlanta has no city HHW facility in the program we verified. Fulton points to annual pollution-prevention days, not a year-round plant.",
        "city_note": "Dried latex may go in Atlanta trash. Liquid chemicals are not a city drop-off we can send you to.",
        "facility": "No permanent city or county HHW depot we can list. Georgia EPD also notes statewide HHW options are limited.",
        "access": "Watch for posted Fulton HHW days and city events. Do not pour chemicals in a drain or storm sewer.",
        "accepted_hint": "Event-based only when a day is posted. Confirm the current flyer.",
        "not_accepted_hint": "There is no everyday Atlanta HHW gate.",
        "fee_note": "Do not invent a drop-off fee. Confirm the event you actually use.",
        "last_verified_at": TODAY,
    },
    {
        "county": "Douglas County",
        "county_slug": "douglas",
        "state": "NE",
        "state_slug": "nebraska",
        "cities": ["omaha"],
        "kind": "county_program",
        "program_name": "Under The Sink — Omaha metro HHW",
        "who_qualifies": "The Omaha path we verified is Under The Sink, a metro HHW facility — confirm your city is listed.",
        "city_note": "This is not Omaha bulky pickup. Latex may have a per-container fee; oil paint is listed separately.",
        "access": "Under The Sink — 4001 S 120th St. Confirm fees and hours on underthesink.org.",
    },
    {
        "county": "El Paso County",
        "county_slug": "el-paso",
        "state": "CO",
        "state_slug": "colorado",
        "cities": ["colorado-springs"],
        "kind": "county_program",
        "program_name": "El Paso County Household Hazardous Waste",
        "who_qualifies": "El Paso County, Colorado residents. This is not El Paso, Texas.",
        "city_note": "Colorado Springs’s verified HHW path is the county facility at 3255 Akers Dr.",
        "access": "County HHW with a posted annual gallon cap. Confirm on elpasoco.com.",
    },
    {
        "county": "Wake County",
        "county_slug": "wake",
        "state": "NC",
        "state_slug": "north-carolina",
        "cities": ["raleigh"],
        "kind": "county_program",
        "program_name": "Wake County Household Hazardous Waste",
        "who_qualifies": "Wake County residents, including Raleigh, at county HHW.",
        "city_note": "Raleigh’s verified HHW path is the county program. Dried latex may be trash; oil paint goes to HHW.",
        "access": "Wake County HHW (South site listed on the county page). Confirm limits on wake.gov.",
    },
    {
        "county": "Virginia Beach",
        "county_slug": "virginia-beach",
        "state": "VA",
        "state_slug": "virginia",
        "cities": ["virginia-beach"],
        "kind": "consolidated",
        "program_name": "Virginia Beach Household Hazardous Waste",
        "who_qualifies": "Virginia Beach residents. Norfolk, Chesapeake, and Hampton are independent cities with their own programs.",
        "city_note": "Virginia Beach is an independent city — there is no surrounding county HHW for this address.",
        "access": "Recycling and Refuse Center HHW with posted weight/gallon caps. Confirm on vbgov.com.",
    },
    {
        "county": "Miami-Dade County",
        "county_slug": "miami-dade",
        "state": "FL",
        "state_slug": "florida",
        "cities": ["miami"],
        "kind": "county_program",
        "program_name": "Miami-Dade Home Chemical Collection Centers",
        "who_qualifies": "Miami-Dade County residents, including the City of Miami.",
        "city_note": "The City of Miami path we verified is the county Home Chemical Collection Centers — not a city-only closet.",
        "access": "County Home Chemical Collection Centers. Confirm sites on miamidade.gov.",
    },
    {
        "county": "Alameda County",
        "county_slug": "alameda",
        "state": "CA",
        "state_slug": "california",
        "cities": ["oakland"],
        "kind": "county_program",
        "program_name": "Alameda County / StopWaste Household Hazardous Waste",
        "who_qualifies": "Alameda County residents, including Oakland, at county HHW.",
        "city_note": "Oakland’s verified HHW path is StopWaste / county HHW, not a city bulky day.",
        "access": "Alameda County HHW — 2100 E. 7th St, Oakland. Confirm on stopwaste.org.",
    },
    {
        "county": "Hennepin County",
        "county_slug": "hennepin",
        "state": "MN",
        "state_slug": "minnesota",
        "cities": ["minneapolis"],
        "kind": "county_program",
        "program_name": "Hennepin County Green Disposal Guide / HHW",
        "who_qualifies": "Hennepin County residents, including Minneapolis.",
        "city_note": "Minneapolis’s verified HHW path is the county program (Bloomington site listed).",
        "access": "Hennepin County HHW — 1400 W 96th St, Bloomington. Confirm hours on hennepin.us.",
    },
    {
        "county": "Tulsa County",
        "county_slug": "tulsa",
        "state": "OK",
        "state_slug": "oklahoma",
        "cities": ["tulsa"],
        "kind": "city_anchor",
        "program_name": "City of Tulsa bulky / Household Pollutant Collection Facility",
        "who_qualifies": "The program we verified is City of Tulsa bulky and HPCF. Other Tulsa County towns must confirm their own HHW.",
        "city_note": "Tulsa bulky latex limits and HPCF are city services, not a countywide depot.",
        "access": "Bulky pickup caps and HPCF at 4502 S Galveston. Confirm on cityoftulsa.org.",
    },
    {
        "county": "Kern County",
        "county_slug": "kern",
        "state": "CA",
        "state_slug": "california",
        "cities": ["bakersfield"],
        "kind": "county_program",
        "program_name": "Kern County Special Waste Facility",
        "who_qualifies": "Kern County residents, including Bakersfield, at the county Special Waste Facility.",
        "city_note": "Bakersfield’s verified HHW path is the county Public Works site.",
        "access": "Kern County Special Waste Facility — 4951 Standard. Confirm on kernpublicworks.com.",
    },
    {
        "county": "Sedgwick County",
        "county_slug": "sedgwick",
        "state": "KS",
        "state_slug": "kansas",
        "cities": ["wichita"],
        "kind": "county_program",
        "program_name": "Sedgwick County Household Hazardous Waste",
        "who_qualifies": "Sedgwick County residents, including Wichita.",
        "city_note": "Wichita’s verified HHW path is the county facility, not city bulky.",
        "access": "Sedgwick County HHW — 801 Stillwell St. Confirm hours on sedgwickcounty.org.",
    },
    {
        "county": "Arapahoe County",
        "county_slug": "arapahoe",
        "state": "CO",
        "state_slug": "colorado",
        "cities": ["aurora"],
        "kind": "city_anchor",
        "program_name": "City of Aurora paint and household chemicals",
        "who_qualifies": "The program we verified is City of Aurora (PaintCare or dry-for-trash). Aurora spans Arapahoe and Adams counties — there is no single Aurora-county depot in that page.",
        "city_note": "Do not use Denver At-Your-Door for an Aurora address. Denver is a different city-county.",
        "access": "PaintCare drop-off or fully dried latex in the Aurora trash cart. Confirm on auroragov.org.",
    },
]


def main() -> None:
    cities = {c["city_slug"]: c for c in json.loads((ROOT / "data" / "geo" / "cities.json").read_text())}
    pages = json.loads((ROOT / "data" / "resolved" / "pages.json").read_text())
    paint = {
        (p["state_slug"], p["city_slug"]): p
        for p in pages
        if p["item_slug"] == "paint-latex" and p.get("indexable")
    }
    hubs = []
    for row in ROWS:
        lead_slug = row["cities"][0]
        lead_city = cities[lead_slug]
        src = paint.get((row["state_slug"], lead_slug))
        city_rows = []
        for slug in row["cities"]:
            c = cities[slug]
            city_rows.append({"city": c["city"], "city_slug": c["city_slug"], "population": c.get("population") or 0})
        hub = {
            "county": row["county"],
            "county_slug": row["county_slug"],
            "state": row["state"],
            "state_slug": row["state_slug"],
            "kind": row["kind"],
            "program_name": row["program_name"],
            "who_qualifies": row["who_qualifies"],
            "city_note": row["city_note"],
            "access": row["access"],
            "cities": city_rows,
            "source_name": row.get("source_name") or (src or {}).get("source_name"),
            "source_url": row.get("source_url") or (src or {}).get("source_url"),
            "facility": row.get("facility") or (src or {}).get("nearest_facility_type"),
            "fee_note": row.get("fee_note") or (src or {}).get("common_disposal_fee"),
            "accepted_hint": row.get("accepted_hint"),
            "not_accepted_hint": row.get("not_accepted_hint"),
            "last_verified_at": row.get("last_verified_at") or (src or {}).get("last_verified_at"),
            "indexable": True,
        }
        if not hub["source_url"]:
            raise SystemExit(f"missing source for {row['county']}")
        hubs.append(hub)
    hubs.sort(key=lambda h: -sum(c["population"] for c in h["cities"]))
    out = ROOT / "data" / "geo" / "county_hhw.json"
    out.write_text(json.dumps(hubs, indent=2) + "\n")
    print(f"Wrote {len(hubs)} county HHW hubs covering {sum(len(h['cities']) for h in hubs)} cities")


if __name__ == "__main__":
    main()
