#!/usr/bin/env python3
"""Upsert verified high-intent city disposal rules — metro wave 6 (2026-08-12).

Cities: cleveland OH, washington DC, newark NJ, st-paul MN, baton-rouge LA,
worcester MA, little-rock AR, tallahassee FL, knoxville TN, akron OH,
dayton OH, fort-lauderdale FL, mobile AL, syracuse NY.

Items: mattress, refrigerator, television, paint-latex, lithium-battery,
sofa, tires, air-conditioner, propane-tank, household-batteries.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = ROOT / "data" / "rules" / "all.json"
VERIFIED = "2026-08-12"
REVIEWER = "metro-wave6"

ITEMS = [
    "mattress",
    "refrigerator",
    "television",
    "paint-latex",
    "lithium-battery",
    "sofa",
    "tires",
    "air-conditioner",
    "propane-tank",
    "household-batteries",
]


def faq(pairs):
    return [{"q": q, "a": a} for q, a in pairs]


def R(city, state, item, badge, hazard, curbside, fee, facility, answer, steps, faqs, src_name, src_url):
    assert item in ITEMS, item
    assert len(steps) == 3, item
    assert 1 <= len(faqs) <= 2, item
    return {
        "item_slug": item,
        "state": state,
        "city_slug": city,
        "zip": None,
        "is_curbside_allowed": curbside,
        "nearest_facility_type": facility[:120],
        "common_disposal_fee": fee[:80],
        "badge": badge,
        "hazard_rating": hazard,
        "answer": answer,
        "steps": steps,
        "faqs": faq(faqs),
        "source_url": src_url,
        "source_name": src_name,
        "last_verified_at": VERIFIED,
        "reviewed_by": REVIEWER,
        "needs_review": False,
    }


# Each city: state + sources + per-item overrides (answer/steps/faqs/fee/facility/curbside/badge/hazard/src)
# Defaults fill from channel templates when a field is omitted.


def cleveland():
    c, st = "cleveland", "OH"
    waste_n, waste_u = (
        "City of Cleveland — Division of Waste Collection",
        "https://www.clevelandohio.gov/city-hall/departments/public-works/divisions/waste/waste",
    )
    return [
        R(c, st, "mattress", "SPECIAL_HANDLING", "Low", True,
          "Included in monthly bulk week (up to 3 items) or free Ridge Rd drop-off (4×/yr)",
          "Cleveland Division of Waste Collection / Ridge Road Transfer Station",
          "Cleveland’s Division of Waste Collection picks up up to three bulk items per home on your regular collection day during the first full week of each month. Mattresses and cloth furniture must be wrapped in plastic. Residents may also drop bulky waste free up to four times per year at the Ridge Road Transfer Station (four cubic yards per visit).",
          ["Wait for bulk week (first full week) on your regular collection day.",
           "Wrap the mattress in plastic; set out within the three-item limit.",
           "Or self-haul to Ridge Road Transfer Station within four free visits per year."],
          [("Unwrapped mattress?", "City requires plastic wrap on mattresses and cloth furniture."),
           ("More than 3 items?", "Use Ridge Road drop-off or call 3-1-1.")],
          waste_n, waste_u),
        R(c, st, "sofa", "SPECIAL_HANDLING", "Low", True,
          "Included in monthly bulk week (up to 3 items)",
          "Cleveland Division of Waste Collection / Ridge Road Transfer Station",
          "Couches and household furniture are Cleveland bulk during the first full week of each month (up to three items on your regular collection day). Cloth furniture must be wrapped in plastic. Excess can go to Ridge Road Transfer Station on free resident visits.",
          ["Confirm bulk week and your regular collection day.",
           "Wrap cloth sofas in plastic; stay within the three-item limit.",
           "Use Ridge Road Transfer Station if you exceed curbside capacity."],
          [("Construction debris?", "No — Division of Waste does not collect C&D with bulk.")],
          waste_n, waste_u),
        R(c, st, "refrigerator", "SPECIAL_HANDLING", "High", True,
          "Bulk week if drained of coolants; or Ridge Road Transfer Station",
          "Cleveland bulk / Ridge Road Transfer Station",
          "Cleveland lists appliances drained of coolants and fluids among bulk waste during monthly bulk week. Refrigerators should not go in trash carts. Confirm Freon handling before set-out or self-haul to Ridge Road Transfer Station.",
          ["Confirm the unit is drained of coolants/fluids per city bulk rules.",
           "Set out during bulk week within the three-item limit, or self-haul to Ridge Road.",
           "Never vent refrigerant; call 3-1-1 with appliance questions."],
          [("Trash cart?", "Never — Freon appliances are bulk/special handling only.")],
          waste_n, waste_u),
        R(c, st, "air-conditioner", "SPECIAL_HANDLING", "High", True,
          "Bulk week if drained of coolants; or Ridge Road Transfer Station",
          "Cleveland bulk / Ridge Road Transfer Station",
          "Window and portable air conditioners follow Cleveland’s appliance bulk pathway — drained of coolants/fluids during monthly bulk week, or taken to Ridge Road Transfer Station. Keep Freon units out of carts and HHW drop boxes.",
          ["Do not place AC units in trash or recycling carts.",
           "Use bulk week set-out or Ridge Road drop-off after coolant rules are met.",
           "Call 3-1-1 for appliance collection questions."],
          [("HHW first Friday?", "Carr Center HHW focuses on chemicals — Freon appliances use bulk/transfer pathways.")],
          waste_n, waste_u),
        R(c, st, "television", "SPECIAL_HANDLING", "Medium", True,
          "Bulk week / Carr Center electronics guidance — confirm acceptance",
          "Cleveland bulk / Carr Center drop-off guidance",
          "Cleveland’s waste guide lists televisions among bulk items during the first full week of each month. Keep TVs out of recycling carts. For electronics beyond bulk, confirm Carr Center options via 3-1-1.",
          ["Set the TV out during bulk week within the three-item limit if using curbside.",
           "Keep electronics out of blue recycling carts.",
           "Confirm Carr Center electronics options via 3-1-1 before self-hauling."],
          [("Recycling cart?", "No — TVs are not curbside recycling in Cleveland.")],
          waste_n, waste_u),
        R(c, st, "tires", "SPECIAL_HANDLING", "Medium", True,
          "Up to 4 passenger tires off-rim during bulk week (call 216-664-3711)",
          "Cleveland Division of Waste Collection tire set-out",
          "Cleveland allows up to four passenger tires without rims during the first full week of each month on your regular collection day. Call (216) 664-3711 to schedule the four-tire pickup. Do not leave tires in recycling drop boxes.",
          ["Remove tires from rims (passenger tires only).",
           "Call (216) 664-3711 to schedule the bulk-week tire pickup.",
           "Set out only during the first full week on your regular collection day."],
          [("Rims on?", "City guidance requires tires off the rim for the scheduled set-out.")],
          waste_n, waste_u),
        R(c, st, "paint-latex", "SPECIAL_HANDLING", "Medium", False,
          "Not Carr Center HHW (no latex paint) — dry empty or retailer/reuse options",
          "Cleveland special-waste / dried latex pathway",
          "Cleveland’s Division of Waste notes Household Hazardous Waste collection on the first Friday of each month does not accept latex paint. Dry small amounts of latex paint solid for trash when allowed, or use reuse/retailer take-back. Never pour paint into storm drains.",
          ["Do not take latex paint to the city’s first-Friday HHW event (not accepted).",
           "Dry small leftover latex solid for trash if your waste guide allows, or find reuse.",
           "Keep liquid paint and oil-based products for proper HHW/special-waste channels."],
          [("Oil-based paint?", "Treat as HHW — different from dried latex; confirm first-Friday accepted list.")],
          waste_n, waste_u),
        R(c, st, "lithium-battery", "BANNED_FROM_LANDFILLS", "High", False,
          "First-Friday HHW / battery recycler — never trash carts",
          "Cleveland HHW first Friday / battery drop-off",
          "Lithium and rechargeable batteries are fire hazards in carts. Cleveland residents should use city-published HHW (first Friday monthly at Carr Center per Division of Waste calendars) or retailer battery take-back — never loose lithium cells in trash or recycling.",
          ["Tape terminals on lithium/rechargeable cells and keep them dry.",
           "Use first-Friday HHW or a battery retailer take-back — not trash carts.",
           "Call 3-1-1 to confirm the next HHW date and accepted battery types."],
          [("Alkaline OK in trash?", "Many communities allow spent alkalines in trash; lithium/rechargeables need special handling.")],
          waste_n, waste_u),
        R(c, st, "household-batteries", "SPECIAL_HANDLING", "Medium", False,
          "Battery drop-off / first-Friday HHW for rechargeables",
          "Cleveland HHW / retailer battery take-back",
          "Household batteries should not be dumped loosely where lithium cells can start fires. Cleveland residents should prefer retailer take-back and city HHW pathways for rechargeable and lithium chemistries; confirm alkaline guidance in the city’s Waste & Recycling Guide.",
          ["Sort lithium/rechargeable batteries away from ordinary trash.",
           "Use retailer take-back or city HHW first-Friday drop-off.",
           "Tape terminals before transport."],
          [("Carr Center?", "First-Friday HHW is listed on Division of Waste calendars — confirm battery acceptance.")],
          waste_n, waste_u),
        R(c, st, "propane-tank", "BANNED_FROM_LANDFILLS", "High", False,
          "HHW / exchange cage — not trash carts or bulk piles",
          "Cleveland HHW / propane exchange",
          "Propane cylinders are pressurized and must not go in Cleveland trash carts, recycling, or bulk piles. Use a propane exchange cage at retailers when possible, or confirm first-Friday HHW acceptance for small cylinders via 3-1-1.",
          ["Do not set propane tanks with trash or monthly bulk.",
           "Prefer empty/exchange cylinders at hardware propane cages.",
           "Confirm HHW acceptance for leftover tanks with 3-1-1."],
          [("Bulk week?", "No — pressurized tanks are not ordinary bulk furniture items.")],
          waste_n, waste_u),
    ]


def washington():
    c, st = "washington", "DC"
    bulk_n, bulk_u = ("DC Department of Public Works — Bulk trash collection", "https://dpw.dc.gov/service/bulk-collections")
    fort_n, fort_u = ("DC DPW — Fort Totten Transfer Station", "https://dpw.dc.gov/service/fort-totten-transfer-station")
    hhw_n, hhw_u = ("DC DPW — Household Hazardous Waste, E-cycling & Document Shredding", "https://dpw.dc.gov/service/household-hazardous-waste-hhw-e-cycling-document-shredding")
    return [
        R(c, st, "mattress", "SPECIAL_HANDLING", "Low", True,
          "Free 311 bulk appointment or Fort Totten resident drop-off",
          "DC DPW bulk collection / Fort Totten Transfer Station",
          "District residents schedule bulk trash collection through DC 311 / DPW for large items including mattresses and box springs. You can also take bulk items without an appointment to Fort Totten Transfer Station (4900 John McCormack Rd NE) during published resident hours. Mattresses do not have to be wrapped in plastic for Fort Totten.",
          ["Book a DPW bulk appointment via 311, or plan a Fort Totten self-haul visit.",
           "Set the mattress out only on your confirmed bulk date, or deliver to Fort Totten.",
           "Keep HHW and e-waste for Special Waste Collection Events — not Fort Totten."],
          [("Fort Totten hours?", "Resident bulk drop-off is typically Tue–Fri 10 a.m.–2 p.m. and Sat 7 a.m.–2 p.m. — confirm on the DPW page."),
           ("Benning Road?", "Benning Road Transfer Station has been temporarily closed; Fort Totten is the active resident bulk site.")],
          bulk_n, bulk_u),
        R(c, st, "sofa", "SPECIAL_HANDLING", "Low", True,
          "Free 311 bulk appointment or Fort Totten resident drop-off",
          "DC DPW bulk collection / Fort Totten Transfer Station",
          "Sofas and other bulky furniture are collected by DC DPW bulk trash (schedule via 311) or accepted at Fort Totten Transfer Station for District residents during published hours. Do not leave furniture on the curb without a scheduled bulk collection.",
          ["Schedule bulk via 311 or self-haul to Fort Totten Transfer Station.",
           "Place items only on the confirmed bulk date if using curbside.",
           "Keep construction debris and HHW out of bulk loads."],
          [("Appointment required?", "Curbside bulk is by appointment; Fort Totten accepts resident bulk without an appointment during hours.")],
          fort_n, fort_u),
        R(c, st, "refrigerator", "SPECIAL_HANDLING", "High", True,
          "311 bulk appointment or Fort Totten (major appliances accepted)",
          "DC DPW bulk / Fort Totten Transfer Station",
          "Major appliances including refrigerators are accepted through DC DPW bulk trash (call 311) and at Fort Totten Transfer Station for residents. DPW’s special-waste page notes large household appliances go to Fort Totten or 311 bulk — not HHW events.",
          ["Empty the refrigerator and secure or remove doors as instructed.",
           "Schedule 311 bulk or deliver to Fort Totten during resident hours.",
           "Do not take Freon appliances to Special Waste Collection Events as HHW substitutes."],
          [("HHW event?", "Large appliances are directed to Fort Totten / 311 bulk, not HHW drop-off.")],
          fort_n, fort_u),
        R(c, st, "air-conditioner", "SPECIAL_HANDLING", "High", True,
          "Call 311 for bulk trash collection appointment",
          "DC DPW 311 bulk collection",
          "DC DPW’s Household Hazardous Waste guidance states air conditioners should be handled by calling 311 for a bulk trash collection appointment — not as HHW at Special Waste Collection Events. Keep the sealed unit intact until collection.",
          ["Call 311 to schedule a DPW bulk trash appointment for the AC unit.",
           "Do not place Freon appliances in trash carts or at HHW events.",
           "Never vent refrigerant yourself."],
          [("Fort Totten?", "Major appliances are listed among Fort Totten acceptable materials; confirm current AC acceptance before hauling.")],
          hhw_n, hhw_u),
        R(c, st, "television", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free registered Special Waste Collection Event (DC residents)",
          "DC DPW Special Waste Collection Events (e-cycling)",
          "TVs and other electronics are collected at DC DPW Special Waste Collection Events (HHW, e-cycling, and shredding). Events require free Eventbrite registration and proof of District residency; recent events have been held at RFK Parking Lot 8. Electronics are not accepted at Fort Totten.",
          ["Register for a Special Waste Collection Event (tinyurl.com/hhw-register or DPW page).",
           "Bring proof of DC residency and arrive in your timed window.",
           "Wipe personal data from devices before drop-off."],
          [("Fort Totten for TVs?", "No — Fort Totten’s unacceptable list includes HHW/e-cycling; use Special Waste events.")],
          hhw_n, hhw_u),
        R(c, st, "tires", "SPECIAL_HANDLING", "Medium", False,
          "Up to 4 tires at Fort Totten during regular business hours",
          "Fort Totten Transfer Station",
          "DPW guidance allows District residents to take up to four tires to Fort Totten Transfer Station during regular business hours. Tires are not accepted at Special Waste Collection Events. Prefer retailer take-back when buying replacements.",
          ["Limit the load to up to four tires for Fort Totten.",
           "Deliver during published Fort Totten resident hours with proof of residency if requested.",
           "Ask tire shops about take-back when replacing tires."],
          [("HHW event tires?", "No — DPW lists tires as not for Special Waste events; use Fort Totten.")],
          fort_n, fort_u),
        R(c, st, "paint-latex", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free registered Special Waste Collection Event",
          "DC DPW Special Waste Collection Events",
          "Latex and oil-based paints are household hazardous waste streams for DPW Special Waste Collection Events. Register in advance, bring proof of DC residency, and keep paint sealed. Do not put liquid paint in trash carts or pour it into drains.",
          ["Register for the next Special Waste Collection Event.",
           "Transport sealed, labeled paint cans upright.",
           "Arrive in your reserved window with proof of residency."],
          [("Commercial paint?", "Events are for DC residents only — no commercial waste.")],
          hhw_n, hhw_u),
        R(c, st, "lithium-battery", "BANNED_FROM_LANDFILLS", "High", False,
          "Free registered Special Waste Collection Event",
          "DC DPW Special Waste Collection Events",
          "Lithium batteries belong at DC DPW Special Waste Collection Events with other HHW — never in trash or recycling carts where they can ignite. Register, tape terminals, and bring proof of District residency.",
          ["Tape lithium battery terminals and bag them safely.",
           "Register for a DPW Special Waste Collection Event.",
           "Drop off during your reserved arrival window with residency proof."],
          [("Trash OK?", "No — lithium batteries are a fire hazard in carts and trucks.")],
          hhw_n, hhw_u),
        R(c, st, "household-batteries", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free registered Special Waste Collection Event / retailer take-back",
          "DC DPW Special Waste Collection Events",
          "Household batteries (especially rechargeable and lithium chemistries) should go to DPW Special Waste Collection Events or retailer take-back programs. Keep batteries out of District trash and recycling carts.",
          ["Sort and tape battery terminals before transport.",
           "Use a registered Special Waste event or retailer battery drop-off.",
           "Bring DC residency proof to DPW events."],
          [("Alkaline?", "Prefer HHW/retailer channels when available; never mix lithium cells into loose trash.")],
          hhw_n, hhw_u),
        R(c, st, "propane-tank", "BANNED_FROM_LANDFILLS", "High", False,
          "Special Waste Collection Event / propane exchange — not Fort Totten trash",
          "DC DPW Special Waste events / propane exchange",
          "Propane tanks are pressurized and must not go in trash carts or ordinary Fort Totten garbage loads. Use retailer propane exchange when possible, or confirm small-cylinder acceptance at DPW Special Waste Collection Events before hauling.",
          ["Prefer empty/exchange cylinders at hardware propane cages.",
           "Confirm Special Waste event acceptance for leftover tanks.",
           "Never puncture or trash a pressurized cylinder."],
          [("Fort Totten?", "HHW streams are not Fort Totten’s pathway — use Special Waste events or exchange.")],
          hhw_n, hhw_u),
    ]



def newark():
    c, st = "newark", "NJ"
    bulk_n, bulk_u = ("City of Newark DPW — What We Pick Up (bulk)", "https://dpw.newarknj.gov/what-we-pick-up/")
    sched_n, sched_u = ("City of Newark DPW — Trash and Bulk Collection Schedule", "https://dpw.newarknj.gov/trash-and-bulk-collection-schedule/")
    centers_n, centers_u = ("City of Newark DPW — Service Centers", "https://dpw.newarknj.gov/service-centers/")
    ecua_n, ecua_u = ("Essex County Utilities Authority — Household Hazardous Waste", "https://www.ecuanj.com/")
    return [
        R(c, st, "mattress", "SPECIAL_HANDLING", "Low", True,
          "Curbside bulk (covered mattresses; up to 3) or DPW service-center drop-off",
          "Newark DPW bulk collection / ward service centers",
          "Newark DPW collects covered mattresses as bulk (up to three mattresses) on scheduled bulk days — Zone A on the first Wednesday and Zone B on the second Wednesday each month. Residences are limited to ten bulk items total. You can also drop items at DPW service centers Monday–Saturday 8 a.m.–3 p.m.",
          ["Cover the mattress and confirm your bulk zone day (1st or 2nd Wednesday).",
           "Set out within the ten-item overall bulk limit (max three mattresses).",
           "Or drop off at a Newark DPW service center during published hours."],
          [("Uncovered mattress?", "DPW specifies covered mattresses for bulk pickup."),
           ("Service centers?", "North, West/Central, South, and East ward centers — see dpw.newarknj.gov/service-centers.")],
          bulk_n, bulk_u),
        R(c, st, "sofa", "SPECIAL_HANDLING", "Low", True,
          "Curbside bulk (up to 10 items) on zone Wednesday",
          "Newark DPW bulk collection / service centers",
          "Couches, tables, chairs, and similar furniture are Newark bulk items. Set them out on your zone’s bulk Wednesday (Zone A first Wednesday; Zone B second Wednesday), staying within the ten-item limit, or use a DPW service center drop-off.",
          ["Identify Zone A vs Zone B for your address.",
           "Set out the sofa on the correct bulk Wednesday within the ten-item limit.",
           "Use a ward service center if you miss curbside or have excess."],
          [("Exceed 10 items?", "Excess must be removed by a private hauler the same day at the owner’s expense.")],
          sched_n, sched_u),
        R(c, st, "refrigerator", "SPECIAL_HANDLING", "High", True,
          "White-goods pickup appointment / service-center guidance",
          "Newark DPW white-goods appointment / service centers",
          "Newark DPW provides a white-goods pickup appointment pathway for appliances. Do not leave Freon refrigerators as ordinary uncovered trash. Schedule white-goods service via DPW’s appointment forms and keep refrigerant sealed until a proper handler takes the unit.",
          ["Use Newark DPW’s white-goods pickup appointment form/process.",
           "Empty food and follow door-safety instructions from DPW.",
           "Never vent Freon; keep the unit out of recycling carts."],
          [("Bulk Wednesday?", "Appliances use the white-goods appointment channel — confirm on DPW service-center pages.")],
          centers_n, centers_u),
        R(c, st, "air-conditioner", "SPECIAL_HANDLING", "High", True,
          "White-goods / appliance appointment — not trash carts",
          "Newark DPW white-goods / appliance pathway",
          "Window and central AC equipment contain refrigerant and should go through Newark DPW’s white-goods/appliance appointment options or a licensed recycler — not loose with ordinary trash.",
          ["Schedule DPW white-goods/appliance service rather than dumping curbside casually.",
           "Keep the sealed Freon unit intact.",
           "Ask about service-center drop-off rules for appliances."],
          [("HHW events?", "Essex County HHW events target chemicals — Freon appliances usually need appliance pathways.")],
          centers_n, centers_u),
        R(c, st, "television", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Essex County HHW events / e-waste recycler — confirm acceptance",
          "Essex County Utilities Authority HHW / e-waste options",
          "Newark residents should keep TVs out of trash and recycling carts. Use Essex County Utilities Authority household hazardous waste / electronics collection opportunities (county events, typically Cedar Grove) or a certified e-waste recycler. Call ECUA at 973-792-9060 for current dates.",
          ["Do not place TVs in Newark trash or recycling carts.",
           "Check the next Essex County HHW/electronics collection date (ECUA).",
           "Bring Essex County residency proof to county events."],
          [("City bulk for TVs?", "Prefer county e-waste/HHW channels; confirm any city electronics rules with DPW at 973-733-3644.")],
          ecua_n, ecua_u),
        R(c, st, "tires", "SPECIAL_HANDLING", "Medium", False,
          "Retailer take-back / private hauler — not standard Newark bulk",
          "Tire retailer / private hauler",
          "Tires are not ordinary Newark furniture bulk. When replacing tires, use retailer take-back. For leftover scrap tires, hire a private hauler that accepts tires rather than leaving them on bulk piles that DPW will not remove.",
          ["Ask the tire shop to take old tires with your purchase.",
           "If leftover, use a private tire hauler — not DPW furniture bulk.",
           "Keep tires out of recycling carts."],
          [("Bulk list?", "DPW bulk examples focus on furniture/mattresses — tires need retailer or private disposal.")],
          bulk_n, bulk_u),
        R(c, st, "paint-latex", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free Essex County HHW collection days (residents)",
          "Essex County Utilities Authority HHW events",
          "Paint and other household hazardous waste from Newark go to Essex County Utilities Authority HHW collection days (commonly hosted in Cedar Grove), not city trash carts. Events are free for Essex County residents with proof of residency; call 973-792-9060 for dates.",
          ["Confirm the next ECUA HHW collection date and location.",
           "Transport sealed paint cans upright; residents only.",
           "Never pour paint into storm drains or Newark trash carts."],
          [("Commercial paint?", "County HHW events exclude commercial/large-quantity generators.")],
          ecua_n, ecua_u),
        R(c, st, "lithium-battery", "BANNED_FROM_LANDFILLS", "High", False,
          "Essex County HHW / retailer battery take-back",
          "Essex County Utilities Authority HHW / retailer take-back",
          "Lithium batteries are a fire risk in compactors. Newark residents should use Essex County HHW collection days or retailer battery take-back — never loose lithium cells in trash or recycling.",
          ["Tape lithium terminals and keep cells dry.",
           "Deliver to ECUA HHW events or a battery retailer drop-off.",
           "Call 973-792-9060 for the next county HHW date."],
          [("Trash carts?", "No — lithium batteries must not go in municipal trash.")],
          ecua_n, ecua_u),
        R(c, st, "household-batteries", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Essex County HHW / retailer take-back",
          "Essex County Utilities Authority HHW / retailer take-back",
          "Household batteries from Newark should be managed through Essex County HHW collections or retailer take-back programs, especially rechargeable and lithium chemistries. Keep batteries out of curbside recycling.",
          ["Sort rechargeable/lithium batteries from trash.",
           "Use ECUA HHW days or store battery drop-off bins.",
           "Tape terminals before transport."],
          [("ECUA phone?", "973-792-9060 for HHW collection information.")],
          ecua_n, ecua_u),
        R(c, st, "propane-tank", "BANNED_FROM_LANDFILLS", "High", False,
          "Propane exchange / Essex County HHW if listed",
          "Propane exchange / ECUA HHW",
          "Propane cylinders must not go in Newark trash, recycling, or furniture bulk piles. Use retailer propane exchange cages for empties, and confirm small-cylinder acceptance at Essex County HHW events before hauling partial tanks.",
          ["Exchange empty cylinders at hardware propane cages when possible.",
           "Confirm ECUA HHW acceptance for leftover tanks.",
           "Never puncture or trash a pressurized cylinder."],
          [("DPW bulk?", "No — pressurized tanks are not furniture bulk.")],
          ecua_n, ecua_u),
    ]


def st_paul():
    c, st = "st-paul", "MN"
    city_n, city_u = ("City of Saint Paul — Recycling & Trash", "https://www.stpaul.gov/departments/public-works/recycling-trash")
    hhw_n, hhw_u = ("Ramsey County — Household Hazardous Waste / Environmental Center", "https://www.ramseycountymn.gov/residents/recycling-waste/collection-sites/household-hazardous-waste")
    ec_n, ec_u = ("Ramsey County Environmental Center", "https://www.ramseycountymn.gov/residents/recycling-waste/environmental-center")
    return [
        R(c, st, "mattress", "SPECIAL_HANDLING", "Low", True,
          "Bulky/hauler collection per Saint Paul Public Works rules — confirm set-out",
          "Saint Paul recycling & trash / licensed hauler bulky service",
          "Saint Paul residents follow City Public Works recycling & trash rules with their licensed hauler for bulky items such as mattresses. Do not dump mattresses in alleys. Confirm bulky pickup limits and set-out day with your hauler or the city’s recycling & trash pages before placing items at the curb.",
          ["Check Saint Paul Public Works recycling & trash guidance for bulky set-out rules.",
           "Schedule or use your hauler’s bulky collection rather than illegal dumping.",
           "Keep mattresses dry and accessible on the confirmed pickup day."],
          [("HHW for mattresses?", "No — mattresses are bulky/trash pathways, not Ramsey County HHW.")],
          city_n, city_u),
        R(c, st, "sofa", "SPECIAL_HANDLING", "Low", True,
          "Bulky/hauler collection per Saint Paul Public Works rules",
          "Saint Paul recycling & trash / licensed hauler bulky service",
          "Sofas and large furniture in Saint Paul are handled through bulky collection with your licensed hauler under city Public Works rules. Confirm the set-out day and item limits before placing furniture at the curb.",
          ["Confirm bulky furniture rules with your Saint Paul hauler / city guidance.",
           "Set out only on the allowed bulky day within published limits.",
           "Donate usable sofas when a reuse program will accept them."],
          [("Alleys?", "Do not abandon furniture in alleys — use scheduled bulky service.")],
          city_n, city_u),
        R(c, st, "refrigerator", "SPECIAL_HANDLING", "High", True,
          "Hauler bulky/appliance pickup or appliance recycler — not HHW chemicals lane",
          "Saint Paul hauler appliance/bulky / appliance recycler",
          "Refrigerators need Freon-aware appliance or bulky service in Saint Paul — not the Ramsey County Environmental Center’s household-chemical stream as a substitute for white-goods recycling. Arrange hauler appliance pickup or a certified recycler; empty food and secure doors.",
          ["Schedule appliance/bulky pickup with your licensed hauler or a recycler.",
           "Empty the unit and follow door-safety rules.",
           "Never vent refrigerant yourself."],
          [("Environmental Center?", "Center focuses on HHW/electronics/recycling/food scraps — confirm large Freon appliances before hauling.")],
          city_n, city_u),
        R(c, st, "air-conditioner", "SPECIAL_HANDLING", "High", True,
          "Hauler appliance/bulky or certified Freon recycler",
          "Saint Paul hauler appliance pathway / Freon recycler",
          "Air conditioners contain refrigerant and must not go in Saint Paul trash or recycling carts. Use your hauler’s appliance/bulky options or a certified Freon recycler; keep the sealed unit intact.",
          ["Do not place AC units in carts.",
           "Book hauler appliance service or a certified recycler.",
           "Keep refrigerant sealed until a qualified handler processes the unit."],
          [("Same as fridge?", "Yes — Freon appliances need appliance pathways, not ordinary trash.")],
          city_n, city_u),
        R(c, st, "television", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free Ramsey County Environmental Center electronics drop-off",
          "Ramsey County Environmental Center — 1700 Kent St, Roseville",
          "Saint Paul residents can drop off televisions and electronics free at the Ramsey County Environmental Center (1700 Kent Street, Roseville), open year-round Tuesday–Friday 11 a.m.–6 p.m. and Saturday 9 a.m.–4 p.m. The center serves Ramsey and other metro counties; keep TVs out of curbside recycling.",
          ["Deliver the TV to 1700 Kent St, Roseville during Environmental Center hours.",
           "Bring it as a Ramsey County / metro resident load — free residential electronics.",
           "Wipe personal data from connected devices before drop-off."],
          [("Hours?", "Tue–Fri 11:00–18:00; Sat 9:00–16:00; closed Sun–Mon and listed holidays.")],
          ec_n, ec_u),
        R(c, st, "tires", "SPECIAL_HANDLING", "Medium", False,
          "Retailer take-back / county scrap-tire options — confirm before hauling",
          "Tire retailer / Ramsey County scrap-tire guidance",
          "Do not put tires in Saint Paul trash or recycling carts. Prefer retailer take-back when replacing tires, and check Ramsey County recycling & waste pages for any scrap-tire collection events before self-hauling.",
          ["Ask the tire shop about take-back with purchase.",
           "Confirm county scrap-tire options if you have extras.",
           "Never illegal-dump tires."],
          [("HHW tires?", "Tires are usually separate from HHW chemical drop-off — confirm county rules.")],
          city_n, city_u),
        R(c, st, "paint-latex", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free Ramsey County Environmental Center HHW drop-off",
          "Ramsey County Environmental Center — 1700 Kent St, Roseville",
          "Bring leftover latex and other household hazardous products from Saint Paul to the Ramsey County Environmental Center HHW drop-off (1700 Kent St, Roseville). County guidance notes dried empty latex containers may go in trash, but product with remaining paint belongs at HHW. Propane tanks also go to the Environmental Center.",
          ["Keep leftover latex sealed; do not pour into drains.",
           "Drop off at the Environmental Center during published HHW hours.",
           "Empty dried containers can follow county trash guidance — liquids go to HHW."],
          [("Fee?", "Residential HHW drop-off at the Environmental Center is free for eligible metro residents.")],
          hhw_n, hhw_u),
        R(c, st, "lithium-battery", "BANNED_FROM_LANDFILLS", "High", False,
          "Free Ramsey County Environmental Center HHW drop-off",
          "Ramsey County Environmental Center — 1700 Kent St, Roseville",
          "Lithium and rechargeable batteries from Saint Paul homes belong at the Ramsey County Environmental Center with other HHW — not in trash or recycling carts where they can start fires.",
          ["Tape lithium terminals and keep batteries dry.",
           "Deliver to 1700 Kent St during Environmental Center hours.",
           "Keep batteries out of curbside carts."],
          [("Trash lithium?", "No — fire hazard; use the Environmental Center.")],
          hhw_n, hhw_u),
        R(c, st, "household-batteries", "BANNED_FROM_LANDFILLS", "Medium", False,
          "Free Ramsey County Environmental Center HHW / battery drop-off",
          "Ramsey County Environmental Center — 1700 Kent St, Roseville",
          "Household batteries should be taken to the Ramsey County Environmental Center with HHW streams. Prefer this pathway for mixed household and rechargeable batteries rather than curbside trash.",
          ["Sort and tape battery terminals.",
           "Drop off at the Ramsey County Environmental Center.",
           "Use retailer take-back only if the chemistry is accepted there."],
          [("Center address?", "1700 Kent Street, Roseville, MN 55113.")],
          hhw_n, hhw_u),
        R(c, st, "propane-tank", "BANNED_FROM_LANDFILLS", "High", False,
          "Free Ramsey County Environmental Center (full or empty tanks)",
          "Ramsey County Environmental Center — 1700 Kent St, Roseville",
          "Ramsey County states all propane tanks (full or empty) can be brought to the Environmental Center for safe disposal — do not put them in Saint Paul trash. Empty non-propane containers may have different trash rules; tanks themselves go to the Center.",
          ["Do not place propane tanks in trash or recycling.",
           "Deliver full or empty tanks to 1700 Kent St during Center hours.",
           "Transport upright and secured in your vehicle."],
          [("Empty tank in trash?", "County guidance sends all propane tanks to the Environmental Center.")],
          hhw_n, hhw_u),
    ]

