#!/usr/bin/env python3
"""Authentic finder growth waves 3–12: secondary drop-offs for single-pin metros.

Portal-sourced only (2026-08-11). One secondary per city when verifiable.
Still skipped after wave 12 fill-ins: san-francisco, oklahoma-city, rochester.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FAC_PATH = ROOT / "data" / "facilities" / "all.json"
ITEMS = {i["slug"] for i in json.loads((ROOT / "data" / "items.json").read_text())}


def mats(*groups):
    out, seen = [], set()
    for g in groups:
        for m in g:
            if m not in ITEMS:
                raise SystemExit(f"unknown material slug: {m}")
            if m not in seen:
                seen.add(m)
                out.append(m)
    return out


# Wave label is documentation only; upsert is by (city_slug, name).
WAVES: dict[int, list[dict]] = {
    3: [
        {
            "name": "Miramar Recycling Center",
            "facility_type": "Recycling / appliance drop-off",
            "city_slug": "san-diego",
            "state": "CA",
            "zip": "92111",
            "address": "5165 Convoy St, San Diego, CA 92111",
            "lat": 32.8354,
            "lng": -117.1524,
            "source_url": "https://www.sandiego.gov/environmental-services/recycling/centers/miramarrecycle",
            "hours": "Mon–Sat 7:00–16:30 (closed listed holidays)",
            "phone": "858-268-8971",
            "accepted_materials": mats(
                [
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "stove",
                    "washer",
                    "dryer",
                    "water-heater",
                    "tires",
                    "cooking-oil",
                ]
            ),
        },
        {
            "name": "Northwest (Bachman) Transfer Station",
            "facility_type": "Municipal transfer station",
            "city_slug": "dallas",
            "state": "TX",
            "zip": "75220",
            "address": "9500 Harry Hines Blvd, Dallas, TX 75220",
            "lat": 32.8473,
            "lng": -96.8744,
            "source_url": "https://dallascityhall.com/departments/sanitation/pages/northwest_bachman.aspx",
            "hours": "Mon–Sat 7:00–16:30; Sun closed",
            "phone": "214-670-6161",
            "accepted_materials": mats(
                [
                    "yard-waste",
                    "tires",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "e-waste-mixed",
                ]
            ),
        },
        {
            "name": "Hornsby Bend Biosolids Management Plant — Yard Trimmings Drop-off",
            "facility_type": "Yard trimmings / brush drop-off",
            "city_slug": "austin",
            "state": "TX",
            "zip": "78725",
            "address": "2210 FM 973, Austin, TX 78725",
            "lat": 30.2101,
            "lng": -97.6379,
            "source_url": "https://www.austintexas.gov/resource-recovery/programs/yard-trimmings-and-large-brush-drop",
            "hours": "Mon–Sat 8:00–15:00 (no appointment)",
            "phone": "512-974-2000",
            "accepted_materials": mats(["yard-waste"]),
        },
        {
            "name": "Trail Ridge Landfill",
            "facility_type": "Municipal landfill",
            "city_slug": "jacksonville",
            "state": "FL",
            "zip": "32234",
            "address": "5110 US Hwy 301 S, Baldwin, FL 32234",
            "lat": 30.2242,
            "lng": -82.0444,
            "source_url": "https://www.jacksonville.gov/departments/office-of-administrative-services/solid-waste/disposal-operations",
            "hours": "Mon–Fri 6:00–19:00; Sat 6:00–13:00; Sun closed",
            "phone": "904-748-6015",
            "accepted_materials": mats(
                [
                    "yard-waste",
                    "tires",
                    "refrigerator",
                    "freezer",
                    "washer",
                    "dryer",
                    "stove",
                    "water-heater",
                ]
            ),
        },
        {
            "name": "Old Hemphill Road Drop-off Station",
            "facility_type": "Municipal drop-off station",
            "city_slug": "fort-worth",
            "state": "TX",
            "zip": "76134",
            "address": "6260 Old Hemphill Rd, Fort Worth, TX 76134",
            "lat": 32.6575,
            "lng": -97.3239,
            "source_url": "https://www.fortworthtexas.gov/departments/environmental-services/solidwaste/dropoff/old-hemphill-drop-off",
            "hours": "Tue–Fri 8:00–17:00; Sat 8:00–12:00; Sun–Mon closed",
            "phone": "817-392-1234",
            "accepted_materials": mats(
                [
                    "yard-waste",
                    "tires",
                    "refrigerator",
                    "air-conditioner",
                    "television",
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "fluorescent-bulbs",
                    "cooking-oil",
                ]
            ),
        },
    ],
    4: [
        {
            "name": "Northeast Citizen Collection Station",
            "facility_type": "Citizen collection station — bulky / e-waste / HHW",
            "city_slug": "el-paso",
            "state": "TX",
            "zip": "79924",
            "address": "4501 Hondo Pass Dr, El Paso, TX 79924",
            "lat": 31.8702,
            "lng": -106.4107,
            "source_url": "https://www.elpasotexas.gov/environmental-services/collection-stations/",
            "hours": "Tue–Sat 8:00–16:00",
            "phone": "915-212-6000",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "e-waste-mixed",
                    "paint-latex",
                    "paint-oil",
                    "motor-oil",
                ]
            ),
        },
        {
            "name": "Farrisview Solid Waste Convenience Center",
            "facility_type": "Municipal convenience center — bulk / yard waste",
            "city_slug": "memphis",
            "state": "TN",
            "zip": "38118",
            "address": "3207 Farrisview Blvd, Memphis, TN 38118",
            "lat": 35.0786,
            "lng": -89.9583,
            "source_url": "https://memphistn.gov/convenience-center-locations-solid-waste/",
            "hours": "Fri–Sun 9:00–15:00 (weather permitting)",
            "phone": "311",
            "accepted_materials": mats(
                ["sofa", "mattress", "yard-waste", "refrigerator", "tires"]
            ),
        },
        {
            "name": "Eagle Rock Convenience Center",
            "facility_type": "Transfer station / convenience center",
            "city_slug": "albuquerque",
            "state": "NM",
            "zip": "87113",
            "address": "6301 Eagle Rock NE, Albuquerque, NM 87113",
            "lat": 35.1875,
            "lng": -106.5741,
            "source_url": "https://www.cabq.gov/solidwaste/trash-collection/trash-drop-off",
            "hours": "Daily 8:00–17:00 (no admittance after 16:30)",
            "phone": "505-768-3925",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "washer",
                    "dryer",
                    "stove",
                    "water-heater",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "e-waste-mixed",
                ]
            ),
        },
        {
            "name": "Los Reales Sustainability Campus — Landfill (Self-Haul)",
            "facility_type": "Landfill / self-haul",
            "city_slug": "tucson",
            "state": "AZ",
            "zip": "85756",
            "address": "5300 E Los Reales Rd, Tucson, AZ 85756",
            "lat": 32.1198,
            "lng": -110.8616,
            "source_url": "https://www.tucsonaz.gov/Departments/Environmental-Services/Los-Reales-Sustainability-Campus/Residential-Self-Hauler-Rates",
            "hours": "Mon–Sat 6:00–17:00; Sun closed",
            "phone": "520-791-4183",
            "accepted_materials": mats(
                [
                    "mattress",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "washer",
                    "dryer",
                    "stove",
                    "tires",
                ]
            ),
        },
        {
            "name": "American Avenue Disposal Site",
            "facility_type": "Landfill",
            "city_slug": "fresno",
            "state": "CA",
            "zip": "93630",
            "address": "18950 W American Ave, Kerman, CA 93630",
            "lat": 36.7272,
            "lng": -120.0894,
            "source_url": "https://www.fresnocountyca.gov/Departments/Public-Works-and-Planning/divisions-of-public-works-and-planning/resources-and-parks-division/landfill-operations",
            "hours": "Mon–Fri 7:00–15:00; Sat 8:00–14:30",
            "phone": "(559) 600-4259",
            "accepted_materials": mats(
                [
                    "mattress",
                    "yard-waste",
                    "stove",
                    "washer",
                    "dryer",
                    "water-heater",
                    "tires",
                ]
            ),
        },
    ],
    5: [
        {
            "name": "North Area Recovery Station (NARS)",
            "facility_type": "Transfer station / recovery",
            "city_slug": "sacramento",
            "state": "CA",
            "zip": "95660",
            "address": "4450 Roseville Road, North Highlands, CA 95660",
            "lat": 38.6417,
            "lng": -121.3736,
            "source_url": "https://wmr.saccounty.gov/pages/nars.aspx",
            "hours": "Mon–Fri 6:30–18:00; Sat–Sun 8:00–18:00",
            "phone": "(916) 875-5555",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "yard-waste",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "washer",
                    "dryer",
                    "dishwasher",
                    "stove",
                    "water-heater",
                    "microwave",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "tires",
                ]
            ),
        },
        {
            "name": "Leaf & Brush Drop-off — Raytown Road",
            "facility_type": "Yard waste drop-off",
            "city_slug": "kansas-city",
            "state": "MO",
            "zip": "64138",
            "address": "10301 Raytown Road, Kansas City, MO 64138",
            "lat": 38.9363,
            "lng": -94.4649,
            "source_url": "https://www.kcmo.gov/city-hall/trash/leaf-brush",
            "hours": "Mon–Fri 8:00–17:00 (fee); Sat free drop-off at 7700 E US-40 Highway 8:00–17:00 for KCMO residents",
            "phone": "311",
            "accepted_materials": mats(["yard-waste"]),
        },
        {
            "name": "Environmental Collection Center (EDCO)",
            "facility_type": "HHW / e-waste collection center",
            "city_slug": "long-beach",
            "state": "CA",
            "zip": "90755",
            "address": "2755 California Avenue, Signal Hill, CA 90755",
            "lat": 33.8073,
            "lng": -118.1807,
            "source_url": "https://www.longbeach.gov/lbrecycles/",
            "hours": "2nd & 4th Sat 9:00–14:00 (closed 4th Sat Nov–Dec)",
            "phone": "(562) 570-2876",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "fluorescent-bulbs",
                    "cooking-oil",
                    "tires",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "e-waste-mixed",
                ]
            ),
        },
        {
            "name": "Davis Street Resource Recovery Complex",
            "facility_type": "Transfer station / bulky drop-off",
            "city_slug": "oakland",
            "state": "CA",
            "zip": "94577",
            "address": "2615 Davis Street, San Leandro, CA 94577",
            "lat": 37.7025,
            "lng": -122.185,
            "source_url": "https://www.oaklandca.gov/topics/garbage-and-recycling",
            "hours": "Mon–Fri 7:00–17:00; Sat 8:00–16:00 (appointment for bulky; free mattress drop-off)",
            "phone": "1-888-962-8559",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "washer",
                    "dryer",
                    "dishwasher",
                    "stove",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tires",
                    "e-waste-mixed",
                ]
            ),
        },
        {
            "name": "City of Tulsa Mulch Site",
            "facility_type": "Yard waste / mulch site",
            "city_slug": "tulsa",
            "state": "OK",
            "zip": "74116",
            "address": "2100 N. 145th E. Ave, Tulsa, OK 74116",
            "lat": 36.141,
            "lng": -95.903,
            "source_url": "https://www.cityoftulsa.org/government/departments/public-works/mulch-site/",
            "hours": "Mon–Tue & Thu–Sun 7:30–16:30; Wed closed",
            "phone": "311",
            "accepted_materials": mats(["yard-waste"]),
        },
    ],
    6: [
        {
            "name": "Roberts Lane Transfer Station",
            "facility_type": "Transfer station",
            "city_slug": "bakersfield",
            "state": "CA",
            "zip": "93308",
            "address": "1900 Roberts Lane, Bakersfield, CA 93308",
            "lat": 35.3865,
            "lng": -119.0185,
            "source_url": "https://www.kernpublicworks.com/Home/Components/FacilityDirectory/FacilityDirectory/260/36513",
            "hours": "Mon 17:00–20:00; Thu 17:00–20:00; Sat 8:00–14:00",
            "phone": "(661) 862-8900",
            "accepted_materials": mats(
                [
                    "mattress",
                    "sofa",
                    "recliner",
                    "refrigerator",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "e-waste-mixed",
                    "paint-latex",
                    "paint-oil",
                ]
            ),
        },
        {
            "name": "Gentilly Landfill",
            "facility_type": "C&D / vegetative debris landfill",
            "city_slug": "new-orleans",
            "state": "LA",
            "zip": "70127",
            "address": "10200 Almonaster Ave, New Orleans, LA 70127",
            "lat": 30.0097,
            "lng": -89.9657,
            "source_url": "https://nola.gov/storm-debris/",
            "hours": "Mon–Fri 7:00–17:00; Sat 7:00–12:00; Sun closed",
            "phone": "(504) 240-0380",
            "accepted_materials": mats(
                [
                    "construction-debris",
                    "lumber",
                    "drywall",
                    "concrete",
                    "asphalt-shingles",
                    "yard-waste",
                ]
            ),
        },
        {
            "name": "Ke'ehi Transfer Station",
            "facility_type": "Transfer station",
            "city_slug": "honolulu",
            "state": "HI",
            "zip": "96819",
            "address": "606 Middle Street, Honolulu, HI 96819",
            "lat": 21.3361,
            "lng": -157.8926,
            "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
            "hours": "Mon–Fri 10:00–18:00; Sat 7:00–18:00; Sun closed",
            "phone": "(808) 768-4884",
            "accepted_materials": mats(
                [
                    "car-battery",
                    "household-batteries",
                    "lithium-battery",
                    "sofa",
                    "mattress",
                    "recliner",
                    "desk",
                    "dining-table",
                    "bookshelf",
                    "carpet",
                    "construction-debris",
                ]
            ),
        },
        {
            "name": "OC HHW Collection Center — Huntington Beach",
            "facility_type": "HHW / e-waste",
            "city_slug": "anaheim",
            "state": "CA",
            "zip": "92647",
            "address": "17121 Nichols Lane, Gate 6, Huntington Beach, CA 92647",
            "lat": 33.7167,
            "lng": -117.9958,
            "source_url": "https://oclandfills.com/hhw",
            "hours": "Tue–Sat 9:00–15:00 (closed major holidays and during rain)",
            "phone": "714-834-4000",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "lithium-battery",
                    "fluorescent-bulbs",
                    "propane-tank",
                    "cooking-oil",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "hard-drive",
                    "e-waste-mixed",
                    "ink-toner",
                    "fire-extinguisher",
                    "medical-sharps",
                    "thermometer-mercury",
                    "smoke-detector",
                ]
            ),
        },
        {
            "name": "Bluegrass Regional Transfer Station",
            "facility_type": "Transfer station",
            "city_slug": "lexington",
            "state": "KY",
            "zip": "40504",
            "address": "1505 Old Frankfort Pike, Lexington, KY 40504",
            "lat": 38.059,
            "lng": -84.5306,
            "source_url": "https://www.lexingtonky.gov/living/waste-collection/about-trash",
            "hours": "Mon–Fri 8:00–17:00; free disposal events Sat 6:00–13:00 (Jan/Apr/Jul/Oct)",
            "phone": "(859) 425-2255",
            "accepted_materials": mats(
                [
                    "mattress",
                    "sofa",
                    "recliner",
                    "tires",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "washer",
                    "dryer",
                    "stove",
                    "water-heater",
                    "propane-tank",
                    "construction-debris",
                    "carpet",
                    "desk",
                    "dining-table",
                ]
            ),
        },
    ],
    7: [
        {
            "name": "Lovelace Materials Recovery Facility and Transfer Station",
            "facility_type": "Transfer station / MRF",
            "city_slug": "stockton",
            "state": "CA",
            "zip": "95336",
            "address": "2323 E. Lovelace Road, Manteca, CA 95336",
            "lat": 37.8483,
            "lng": -121.2494,
            "source_url": "https://sjgov.org/department/pwk/solid-waste/san-joaquin-county-solid-waste-facilities/lovelace-mrf-and-transfer-station",
            "hours": "Mon–Sun 7:00–16:00 (closed Easter, Thanksgiving, Christmas, New Year's Day)",
            "phone": "(209) 982-5770",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "tires",
                    "refrigerator",
                    "freezer",
                    "air-conditioner",
                    "television",
                    "computer-monitor",
                    "e-waste-mixed",
                    "construction-debris",
                    "lumber",
                    "drywall",
                    "concrete",
                    "yard-waste",
                ]
            ),
        },
        {
            "name": "Agua Mansa Transfer Station",
            "facility_type": "Transfer station / free bulky drop-off",
            "city_slug": "riverside",
            "state": "CA",
            "zip": "92509",
            "address": "1830 Agua Mansa Road, Riverside, CA 92509",
            "lat": 34.027,
            "lng": -117.3772,
            "source_url": "https://riversideca.gov/publicworks/trash-recycling/clean-riverside",
            "hours": "3rd Sat monthly 8:00–16:00 free bulky; facility Mon–Fri 7:00–18:00, Sat 7:00–16:30, Sun 8:00–15:00",
            "phone": "(951) 826-5311",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "television",
                    "computer-monitor",
                    "refrigerator",
                    "freezer",
                    "tires",
                    "yard-waste",
                    "carpet",
                    "desk",
                    "dining-table",
                    "exercise-equipment",
                ]
            ),
        },
        {
            "name": "OC HHW Collection Center — Huntington Beach",
            "facility_type": "HHW / e-waste",
            "city_slug": "santa-ana",
            "state": "CA",
            "zip": "92647",
            "address": "17121 Nichols Lane, Gate 6, Huntington Beach, CA 92647",
            "lat": 33.7167,
            "lng": -117.9958,
            "source_url": "https://oclandfills.com/hhw",
            "hours": "Tue–Sat 9:00–15:00 (closed major holidays and during rain)",
            "phone": "714-834-4000",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "lithium-battery",
                    "fluorescent-bulbs",
                    "propane-tank",
                    "cooking-oil",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "hard-drive",
                    "e-waste-mixed",
                    "ink-toner",
                ]
            ),
        },
        {
            "name": "OC HHW Collection Center — Anaheim",
            "facility_type": "HHW / e-waste",
            "city_slug": "irvine",
            "state": "CA",
            "zip": "92806",
            "address": "1071 N. Blue Gum Street, Anaheim, CA 92806",
            "lat": 33.85,
            "lng": -117.85,
            "source_url": "https://oclandfills.com/hhw",
            "hours": "Tue–Sat 9:00–15:00 (closed major holidays and during rain)",
            "phone": "714-834-4000",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "lithium-battery",
                    "fluorescent-bulbs",
                    "propane-tank",
                    "cooking-oil",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "microwave",
                    "hard-drive",
                    "e-waste-mixed",
                    "ink-toner",
                ]
            ),
        },
        {
            "name": "Porter Road Transfer Station — Orange County HHW",
            "facility_type": "Transfer station / HHW drop-off",
            "city_slug": "orlando",
            "state": "FL",
            "zip": "32818",
            "address": "1326 Good Homes Road, Orlando, FL 32818",
            "lat": 28.5586,
            "lng": -81.5049,
            "source_url": "https://www.orlando.gov/Our-Government/Departments-Offices/Public-Works/Solid-Waste/Too-Toxic-to-Trash",
            "hours": "Mon–Sat 8:00–17:00",
            "phone": "407-836-6601",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "household-batteries",
                    "lithium-battery",
                    "fluorescent-bulbs",
                    "propane-tank",
                ]
            ),
        },
    ],
    8: [
        {
            "name": "Essex County Electronic Recycling Depot (Newark DPW)",
            "facility_type": "E-waste / battery drop-off",
            "city_slug": "jersey-city",
            "state": "NJ",
            "zip": "07114",
            "address": "62 Frelinghuysen Avenue, Newark, NJ 07114",
            "lat": 40.7137,
            "lng": -74.1888,
            "source_url": "https://dpw.newarknj.gov/what-we-pick-up/",
            "hours": "Mon–Fri 8:00–16:00; Sat 8:00–12:30",
            "phone": "973-733-3644",
            "accepted_materials": mats(
                [
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "e-waste-mixed",
                    "car-battery",
                ]
            ),
        },
        {
            "name": "Orange County Eubanks Road Waste & Recycling Center — HHW",
            "facility_type": "County convenience center / HHW",
            "city_slug": "durham",
            "state": "NC",
            "zip": "27516",
            "address": "1518 Eubanks Road, Chapel Hill, NC 27516",
            "lat": 35.9700,
            "lng": -79.0828,
            "source_url": "https://www.orangecountync.gov/954/Hazardous-Household-Wastes",
            "hours": "Mon/Tue/Thu/Fri 7:00–18:00; Sat 7:00–17:00; Sun 13:00–18:00; closed Wed",
            "phone": "919-968-2788",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "fluorescent-bulbs",
                    "propane-tank",
                ]
            ),
        },
        {
            "name": "St. Louis County HHW — North County (Florissant)",
            "facility_type": "Household hazardous waste drop-off",
            "city_slug": "st-louis",
            "state": "MO",
            "zip": "63033",
            "address": "4100 Seven Hills Drive, Florissant, MO 63033",
            "lat": 38.7759,
            "lng": -90.2765,
            "source_url": "https://stlouiscountymo.gov/st-louis-county-departments/public-health/environmental-services/household-hazardous-waste/",
            "hours": "By appointment — schedule at hhwstl.com or call 314-615-8958",
            "phone": "314-615-8958",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "pool-chemicals",
                    "gasoline",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "lithium-battery",
                    "fluorescent-bulbs",
                    "propane-tank",
                ]
            ),
        },
        {
            "name": "East Side Transfer Station — residential drop-off",
            "facility_type": "Municipal transfer station",
            "city_slug": "buffalo",
            "state": "NY",
            "zip": "14203",
            "address": "793 South Ogden Street, Buffalo, NY 14203",
            "lat": 42.8780,
            "lng": -78.8013,
            "source_url": "https://www.buffalony.gov/382/Streets-Sanitation",
            "hours": "Mon–Fri 7:00–9:00 & 13:00–15:00; Sat 8:00–12:00",
            "phone": "716-823-0795",
            "accepted_materials": mats(
                ["mattress", "box-spring", "sofa", "recliner", "carpet", "yard-waste"]
            ),
        },
        {
            "name": "Otay Landfill — self-haul",
            "facility_type": "Landfill / bulky drop-off",
            "city_slug": "chula-vista",
            "state": "CA",
            "zip": "91911",
            "address": "1700 Maxwell Road, Chula Vista, CA 91911",
            "lat": 32.5988,
            "lng": -117.0177,
            "source_url": "https://www.chulavistaca.gov/departments/sustainability/trash/self-hauling-options",
            "hours": "Mon–Fri 7:00–16:00; Sat 8:00–15:30 (confirm before visit)",
            "phone": "619-421-3773",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "washer",
                    "dryer",
                    "stove",
                ]
            ),
        },
    ],
    9: [
        {
            "name": "Hoffman Road Landfill",
            "facility_type": "Municipal landfill — bulky/residential",
            "city_slug": "toledo",
            "state": "OH",
            "zip": "43611",
            "address": "3962 Hoffman Road, Toledo, OH 43611",
            "lat": 41.6970,
            "lng": -83.5046,
            "source_url": "https://toledo.oh.gov/residents/neighborhoods/trash-recycling/hoffman-road-landfill",
            "hours": "Residential disposal 8:00–15:00; plus city-sponsored free disposal days",
            "phone": "419-936-3077",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "tires",
                    "tire-rims",
                ]
            ),
        },
        {
            "name": "Dane County Landfill & C&D Facility",
            "facility_type": "County landfill / construction drop-off",
            "city_slug": "madison",
            "state": "WI",
            "zip": "53718",
            "address": "7102 Maahic Way, Madison, WI 53718",
            "lat": 43.0450,
            "lng": -89.2551,
            "source_url": "https://landfill.danecounty.gov/about/location",
            "hours": "Mon–Fri 6:30–15:15; Sat 8:00–10:45",
            "phone": "608-838-9555",
            "accepted_materials": mats(["yard-waste", "carpet"]),
        },
        {
            "name": "Pinellas County Solid Waste Disposal Complex",
            "facility_type": "County landfill / transfer scalehouse",
            "city_slug": "st-petersburg",
            "state": "FL",
            "zip": "33716",
            "address": "3095 114th Avenue North, St. Petersburg, FL 33716",
            "lat": 27.8761,
            "lng": -82.6339,
            "source_url": "https://pinellas.gov/solid-waste-disposal-complex-hours/",
            "hours": "Mon–Fri 6:00–18:00; Sat 7:00–17:00",
            "phone": "727-464-7500",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "refrigerator",
                    "freezer",
                    "washer",
                    "dryer",
                    "stove",
                    "tires",
                    "tire-rims",
                    "yard-waste",
                ]
            ),
        },
        {
            "name": "SPSA Regional Landfill — HHW & e-waste",
            "facility_type": "Regional landfill / transfer / HHW",
            "city_slug": "norfolk",
            "state": "VA",
            "zip": "23434",
            "address": "1 Bob Foeller Drive, Suffolk, VA 23434",
            "lat": 36.7552,
            "lng": -76.5168,
            "source_url": "https://www.spsava.gov/193/Regional-Landfill",
            "hours": "Mon–Fri 8:00–16:00; Sat 8:00–12:00 (HHW & e-waste same schedule)",
            "phone": "757-961-3683",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "fluorescent-bulbs",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "e-waste-mixed",
                    "tires",
                    "tire-rims",
                ]
            ),
        },
        {
            "name": "Ada County Landfill (main scalehouse)",
            "facility_type": "County landfill — self-haul",
            "city_slug": "boise",
            "state": "ID",
            "zip": "83714",
            "address": "10300 North Seamans Gulch Road, Boise, ID 83714",
            "lat": 43.6936,
            "lng": -116.2783,
            "source_url": "https://adacounty.id.gov/landfill/contact-connect/landfill-hours-of-operations/",
            "hours": "Mon–Fri 7:00–18:00; Sat 8:00–18:00",
            "phone": "208-577-4725",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "refrigerator",
                    "washer",
                    "dryer",
                    "stove",
                    "tires",
                ]
            ),
        },
    ],
    10: [
        {
            "name": "Spokane County Valley Transfer & Recycling Station",
            "facility_type": "Regional transfer station / HHW (weekends)",
            "city_slug": "spokane",
            "state": "WA",
            "zip": "99216",
            "address": "3941 North Sullivan Road, Spokane Valley, WA 99216",
            "lat": 47.6923,
            "lng": -117.1996,
            "source_url": "https://www.spokanecounty.gov/4637/Disposal-Transfer-Stations",
            "hours": "Daily 7:30–17:00 (Apr–Oct); winter hours shorter; HHW Sat–Sun only",
            "phone": "509-477-6800",
            "accepted_materials": mats(
                [
                    "paint-latex",
                    "paint-oil",
                    "pesticides",
                    "herbicides",
                    "motor-oil",
                    "antifreeze",
                    "car-battery",
                    "household-batteries",
                    "fluorescent-bulbs",
                    "yard-waste",
                    "tires",
                ]
            ),
        },
        {
            "name": "Henrico Charles City Road Public Use Area",
            "facility_type": "County public use / transfer area",
            "city_slug": "richmond",
            "state": "VA",
            "zip": "23231",
            "address": "2075 Charles City Road, Henrico, VA 23231",
            "lat": 37.5102,
            "lng": -77.3701,
            "source_url": "https://henrico.gov/utility/solid-waste/hours-of-operation-and-holiday-schedule/",
            "hours": "Daily 7:30–19:00",
            "phone": "804-222-7739",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "motor-oil",
                    "gasoline",
                    "paint-oil",
                ]
            ),
        },
        {
            "name": "Pierce County Hidden Valley Transfer Station",
            "facility_type": "Regional transfer station",
            "city_slug": "tacoma",
            "state": "WA",
            "zip": "98375",
            "address": "17925 Meridian Avenue East, Puyallup, WA 98375",
            "lat": 47.1041,
            "lng": -122.2941,
            "source_url": "https://www.piercecountywa.gov/1541/Transfer-Stations",
            "hours": "Daily 8:00–17:45; e-waste Tue & Thu 8:00–12:00 & 13:00–17:00",
            "phone": "253-847-7555",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "television",
                    "computer-monitor",
                    "laptop",
                    "e-waste-mixed",
                    "refrigerator",
                    "tires",
                ]
            ),
        },
        {
            "name": "Metro Central Transfer Station — SCRUB events",
            "facility_type": "Municipal transfer station (scheduled public days)",
            "city_slug": "des-moines",
            "state": "IA",
            "zip": "50313",
            "address": "4198 Delaware Avenue, Des Moines, IA 50313",
            "lat": 41.6279,
            "lng": -93.5813,
            "source_url": "https://www.dsm.city/departments/public_works/garbage_recycling/scrub_events/",
            "hours": "3rd Saturday monthly Mar–Nov 7:00–14:00 (Des Moines residents; proof of residency)",
            "phone": "515-283-4950",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "television",
                    "computer-monitor",
                    "paint-latex",
                    "paint-oil",
                    "motor-oil",
                    "pesticides",
                    "tires",
                ]
            ),
        },
        {
            "name": "Salt Lake Valley Transfer Station",
            "facility_type": "County transfer station / glass drop-off",
            "city_slug": "salt-lake-city",
            "state": "UT",
            "zip": "84119",
            "address": "502 West 3300 South, Salt Lake City, UT 84119",
            "lat": 40.6994,
            "lng": -111.9256,
            "source_url": "https://slco.org/recycle/",
            "hours": "Mon–Fri 7:00–17:00; 1st & 3rd Sat 7:00–11:00",
            "phone": "385-468-6370",
            "accepted_materials": mats(["yard-waste"]),
        },
    ],
    11: [
        {
            "name": "Ensley District Waste Roll-off — bulky drop-off",
            "facility_type": "Municipal district roll-off / bulky",
            "city_slug": "birmingham",
            "state": "AL",
            "zip": "35214",
            "address": "1044 Avenue West, Birmingham, AL 35214",
            "lat": 33.5198,
            "lng": -86.8772,
            "source_url": "https://www.birminghamal.gov/government/city-departments/department-public-works/waste-services/illegal-dumping",
            "hours": "Mon–Fri 7:00–16:00",
            "phone": "311",
            "accepted_materials": mats(
                ["mattress", "box-spring", "sofa", "recliner", "carpet", "yard-waste"]
            ),
        },
        {
            "name": "Kent County Recycling & Education Center — drop-off station",
            "facility_type": "County recycling drop-off center",
            "city_slug": "grand-rapids",
            "state": "MI",
            "zip": "49504",
            "address": "977 Wealthy Street SW, Grand Rapids, MI 49504",
            "lat": 42.9562,
            "lng": -85.6844,
            "source_url": "https://www.kentcountymi.gov/657/Drop-off-Stations",
            "hours": "Mon–Fri 7:30–16:30",
            "phone": "616-632-7920",
            "accepted_materials": mats(
                [
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "tablet",
                    "smartphone",
                    "e-waste-mixed",
                ]
            ),
        },
        {
            "name": "Rhode Island Resource Recovery Corporation — Central Landfill SVA",
            "facility_type": "State landfill / small-vehicle drop-off",
            "city_slug": "providence",
            "state": "RI",
            "zip": "02919",
            "address": "65 Shun Pike, Johnston, RI 02919",
            "lat": 41.8001,
            "lng": -71.5511,
            "source_url": "https://www.rirrc.org/about/facilities-hours-directions/",
            "hours": "Mon–Fri 6:00–15:45; Sat 6:00–12:00",
            "phone": "401-942-1430",
            "accepted_materials": mats(
                [
                    "television",
                    "computer-monitor",
                    "laptop",
                    "desktop-computer",
                    "printer",
                    "refrigerator",
                    "freezer",
                    "washer",
                    "dryer",
                    "stove",
                    "tires",
                    "tire-rims",
                    "yard-waste",
                    "paint-latex",
                    "paint-oil",
                    "motor-oil",
                    "pesticides",
                ]
            ),
        },
        {
            "name": "Chattanooga Refuse Collection Center — Airport Road",
            "facility_type": "Municipal bulky refuse drop-off",
            "city_slug": "chattanooga",
            "state": "TN",
            "zip": "37421",
            "address": "4276 Airport Road, Chattanooga, TN 37421",
            "lat": 35.0324,
            "lng": -85.2017,
            "source_url": "https://chattanooga.gov/services/waste-recycling/refuse-collection-centers",
            "hours": "Tue–Fri 10:00–18:00; Sat 9:00–18:00; Sun 13:00–17:00; closed Mon",
            "phone": "423-643-6311",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "washer",
                    "dryer",
                    "stove",
                    "microwave",
                    "tires",
                    "tire-rims",
                    "carpet",
                ]
            ),
        },
    ],
    12: [
        {
            "name": "Guadalupe Rubbish Disposal — Guadalupe Landfill",
            "facility_type": "Landfill / C&D and bulky self-haul",
            "city_slug": "san-jose",
            "state": "CA",
            "zip": "95120",
            "address": "15999 Guadalupe Mines Rd, San Jose, CA 95120",
            "lat": 37.1778,
            "lng": -121.8447,
            "source_url": "https://www.sanjoseca.gov/Home/Components/BusinessDirectory/BusinessDirectory/217/330",
            "hours": "Mon–Sat 8:00–16:00",
            "phone": "408-268-1666",
            "accepted_materials": mats(
                [
                    "construction-debris",
                    "mattress",
                    "sofa",
                    "tires",
                    "refrigerator",
                ]
            ),
        },
        {
            "name": "Denver Arapahoe Disposal Site (DADS)",
            "facility_type": "Regional landfill / drop-off",
            "city_slug": "aurora",
            "state": "CO",
            "zip": "80016",
            "address": "3500 S Gun Club Rd, Aurora, CO 80016",
            "lat": 39.6464,
            "lng": -104.7156,
            "source_url": "https://www.auroragov.org/residents/trash___recycling/recycling_opportunities/recycling_drop-_off",
            "hours": "Mon–Fri 6:00–20:30; Sat 7:00–17:00",
            "phone": "720-876-2650",
            # Type I landfill — conservative bulky/MSW set; confirm fees before visit
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "tires",
                    "refrigerator",
                    "washer",
                    "dryer",
                    "stove",
                ]
            ),
        },
        {
            "name": "Cefe Valenzuela Landfill",
            "facility_type": "Municipal landfill",
            "city_slug": "corpus-christi",
            "state": "TX",
            "zip": "78380",
            "address": "2397 County Road 20, Robstown, TX 78380",
            "lat": 27.6367,
            "lng": -97.5681,
            "source_url": "https://www.corpuschristitx.gov/department-directory/solid-waste-services/landfill-and-collection-centers/",
            "hours": "Daily 6:00–18:00 (confirm holiday schedule on city site)",
            "phone": "361-826-2489",
            "accepted_materials": mats(
                [
                    "mattress",
                    "box-spring",
                    "sofa",
                    "recliner",
                    "carpet",
                    "yard-waste",
                    "tires",
                    "refrigerator",
                    "washer",
                    "dryer",
                    "stove",
                ]
            ),
        },
        {
            "name": "Public Recycling Dumpster — Findlay Market",
            "facility_type": "Public recycling drop-off",
            "city_slug": "cincinnati",
            "state": "OH",
            "zip": "45202",
            "address": "1817 Race St, Cincinnati, OH 45202",
            "lat": 39.1151,
            "lng": -84.519,
            "source_url": "https://www.cincinnati-oh.gov/recycling/public-dropoff/public-recycling-dumpsters/",
            "hours": "24 hours",
            "phone": "513-765-1212",
            "accepted_materials": mats(["cardboard", "glass-bottles"]),
        },
    ],
}


def main() -> None:
    facilities = json.loads(FAC_PATH.read_text())
    by_key = {(f.get("city_slug"), f.get("name")): i for i, f in enumerate(facilities)}
    added = updated = 0
    per_wave: dict[int, int] = {}
    for wave, rows in sorted(WAVES.items()):
        n = 0
        for row in rows:
            key = (row["city_slug"], row["name"])
            if key in by_key:
                facilities[by_key[key]] = {**facilities[by_key[key]], **row}
                updated += 1
            else:
                facilities.append(row)
                by_key[key] = len(facilities) - 1
                added += 1
            n += 1
        per_wave[wave] = n

    FAC_PATH.write_text(json.dumps(facilities, indent=2) + "\n")
    print(f"Facilities: {len(facilities)} (added {added}, updated {updated})")
    for w, n in per_wave.items():
        print(f"  wave {w}: {n} rows")


if __name__ == "__main__":
    main()
