#!/usr/bin/env python3
"""Full .gov drop-off inventory for 24 southeast/south metros (2026-08-11).

Adds permanent convenience centers, transfer stations, HHW, MMRF, and landfill
public sites verified against official city/county pages.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FAC_PATH = ROOT / "data" / "facilities" / "all.json"
ITEMS = {i["slug"] for i in json.loads((ROOT / "data" / "items.json").read_text())}

HHW = [
    "paint-latex",
    "paint-oil",
    "pesticides",
    "herbicides",
    "pool-chemicals",
    "gasoline",
    "motor-oil",
    "antifreeze",
    "car-battery",
    "household-batteries",
    "lithium-battery",
    "fluorescent-bulbs",
    "propane-tank",
    "cooking-oil",
]
E_WASTE = [
    "television",
    "computer-monitor",
    "laptop",
    "desktop-computer",
    "printer",
    "tablet",
    "smartphone",
    "microwave",
    "hard-drive",
    "e-waste-mixed",
    "ink-toner",
]
BULKY = ["mattress", "box-spring", "sofa", "recliner", "carpet", "yard-waste"]
APPLIANCE = [
    "refrigerator",
    "freezer",
    "air-conditioner",
    "washer",
    "dryer",
    "dishwasher",
    "stove",
    "water-heater",
]
TIRES = ["tires", "tire-rims"]
RECYCLE = ["cardboard", "glass-bottles"]


def mats(*groups):
    out, seen = [], set()
    for g in groups:
        for m in g:
            if m not in ITEMS:
                raise SystemExit(f"unknown slug {m}")
            if m not in seen:
                seen.add(m)
                out.append(m)
    return out


FACILITIES: list[dict] = [
    # ── Charlotte / Mecklenburg (wipeoutwaste.mecknc.gov) ──
    {
        "name": "Compost Central Full-Service Recycling Center",
        "facility_type": "Full-service recycling / HHW / bulky",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28214",
        "address": "140 Valleydale Road, Charlotte, NC 28214",
        "lat": 35.312,
        "lng": -80.958,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Mon–Sat 7:00–16:00",
        "phone": "980-314-3867",
        "accepted_materials": mats(HHW, E_WASTE, BULKY, APPLIANCE, TIRES),
    },
    {
        "name": "Foxhole Full-Service — Pence Road",
        "facility_type": "Full-service recycling / HHW / bulky",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28215",
        "address": "8007 Pence Road, Charlotte, NC 28215",
        "lat": 35.268,
        "lng": -80.748,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Mon–Sat 7:00–16:00",
        "phone": "980-314-3867",
        "accepted_materials": mats(HHW, E_WASTE, BULKY, APPLIANCE, TIRES),
    },
    {
        "name": "North Mecklenburg Full-Service Recycling Center",
        "facility_type": "Full-service recycling / HHW / bulky",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28078",
        "address": "12300 N. Statesville Road, Huntersville, NC 28078",
        "lat": 35.412,
        "lng": -80.842,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Mon–Sat 7:00–16:00",
        "phone": "980-314-3867",
        "accepted_materials": mats(HHW, E_WASTE, BULKY, APPLIANCE, TIRES),
    },
    {
        "name": "William R. Davie Staffed Recycling Center",
        "facility_type": "Staffed recycling drop-off center",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28226",
        "address": "4635 Pineville-Matthews Road, Charlotte, NC 28226",
        "lat": 35.108,
        "lng": -80.798,
        "source_url": "https://wipeoutwaste.mecknc.gov/facility/william-r-davie-staffed-recycling-center",
        "hours": "Mon/Tue/Thu/Fri/Sat 9:00–17:00; closed Wed & Sun",
        "phone": "980-314-3867",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Self-Service Recycling — Seigle Avenue",
        "facility_type": "Self-service curbside recycling drop-off",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28205",
        "address": "932 Seigle Avenue, Charlotte, NC 28205",
        "lat": 35.218,
        "lng": -80.812,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Park hours — curbside recyclables only",
        "phone": "980-314-3867",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Self-Service Recycling — Monroe Road",
        "facility_type": "Self-service curbside recycling drop-off",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28212",
        "address": "8711 Monroe Road, Charlotte, NC 28212",
        "lat": 35.178,
        "lng": -80.748,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Park hours — curbside recyclables only",
        "phone": "980-314-3867",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Self-Service Recycling — Park Road",
        "facility_type": "Self-service curbside recycling drop-off",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28210",
        "address": "6220 Park Road, Charlotte, NC 28210",
        "lat": 35.128,
        "lng": -80.848,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Park hours — curbside recyclables only",
        "phone": "980-314-3867",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Self-Service Recycling — Rocky River Road",
        "facility_type": "Self-service curbside recycling drop-off",
        "city_slug": "charlotte",
        "state": "NC",
        "zip": "28213",
        "address": "2900 Rocky River Road, Charlotte, NC 28213",
        "lat": 35.288,
        "lng": -80.768,
        "source_url": "https://wipeoutwaste.mecknc.gov/where-can-i-recycle",
        "hours": "Park hours — curbside recyclables only",
        "phone": "980-314-3867",
        "accepted_materials": mats(RECYCLE),
    },
    # ── Raleigh / Wake County (wake.gov) ──
    *[
        {
            "name": f"Wake County Convenience Center — Site {n}",
            "facility_type": "County convenience center — trash / recycling",
            "city_slug": "raleigh",
            "state": "NC",
            "zip": z,
            "address": addr,
            "lat": lat,
            "lng": lng,
            "source_url": "https://www.wake.gov/departments-government/solid-waste-management/facilities/convenience-centers",
            "hours": "Daily 7:00–19:00",
            "phone": "919-856-7400",
            "accepted_materials": mats(BULKY, RECYCLE),
        }
        for n, addr, z, lat, lng in [
            (1, "10505 Old Stage Road, Raleigh, NC 27603", "27603", 35.612, -78.712),
            (2, "6120 Old Smithfield Road, Apex, NC 27539", "27539", 35.648, -78.758),
            (3, "266 Aviation Parkway, Morrisville, NC 27560", "27560", 35.848, -78.812),
            (4, "3600 Yates Mill Pond Road, Raleigh, NC 27606", "27606", 35.728, -78.712),
            (5, "8401 Battle Bridge Road, Raleigh, NC 27610", "27610", 35.768, -78.568),
            (6, "3913 Lillie Liles Road, Wake Forest, NC 27587", "27587", 35.948, -78.568),
            (7, "9024 Deponie Drive, Raleigh, NC 27614", "27614", 35.912, -78.612),
            (8, "2001 Durham Road/Hwy. 98, Wake Forest, NC 27587", "27587", 35.968, -78.512),
            (9, "3337 New Hill-Holleman Road, New Hill, NC 27562", "27562", 35.688, -78.912),
            (10, "5216 Knightdale-Eagle Rock Road, Knightdale, NC 27545", "27545", 35.788, -78.468),
            (11, "5051 Wendell Blvd./Business 64, Wendell, NC 27591", "27591", 35.780, -78.370),
        ]
    ],
    {
        "name": "North Wake Multi-Material Recycling Facility",
        "facility_type": "MMRF — appliances / e-waste / recyclables",
        "city_slug": "raleigh",
        "state": "NC",
        "zip": "27614",
        "address": "9029 Deponie Drive, Raleigh, NC 27614",
        "lat": 35.912,
        "lng": -78.608,
        "source_url": "https://www.wake.gov/departments-government/solid-waste-management/facilities/multi-material-recycling-facilities",
        "hours": "Mon–Sat 8:00–16:00",
        "phone": "919-856-7400",
        "accepted_materials": mats(E_WASTE, APPLIANCE, TIRES, ["motor-oil", "antifreeze"]),
    },
    {
        "name": "North Wake Household Hazardous Waste Facility",
        "facility_type": "Household hazardous waste drop-off",
        "city_slug": "raleigh",
        "state": "NC",
        "zip": "27614",
        "address": "9037 Deponie Drive, Raleigh, NC 27614",
        "lat": 35.914,
        "lng": -78.610,
        "source_url": "https://www.wake.gov/departments-government/solid-waste-management/facilities/household-hazardous-waste-facilities",
        "hours": "Sat 8:00–16:00 (Wake County residents only)",
        "phone": "919-856-7400",
        "accepted_materials": mats(HHW),
    },
    {
        "name": "East Wake Household Hazardous Waste Facility",
        "facility_type": "Household hazardous waste drop-off",
        "city_slug": "raleigh",
        "state": "NC",
        "zip": "27591",
        "address": "5051 Wendell Blvd., Wendell, NC 27591",
        "lat": 35.780,
        "lng": -78.368,
        "source_url": "https://www.wake.gov/departments-government/solid-waste-management/facilities/household-hazardous-waste-facilities",
        "hours": "Sat–Sun 8:00–16:00 (Wake County residents only)",
        "phone": "919-856-7400",
        "accepted_materials": mats(HHW),
    },
    # ── Honolulu (honolulu.gov) ──
    {
        "name": "Waiʻanae Convenience Center",
        "facility_type": "City convenience center — bulky / green waste / special waste",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96792",
        "address": "85-572 Waiʻanae Valley Road, Waiʻanae, HI 96792",
        "lat": 21.438,
        "lng": -158.188,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 696-4203",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank", "yard-waste"]),
    },
    {
        "name": "Waipahu Convenience Center",
        "facility_type": "City convenience center — bulky / green waste / special waste",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96797",
        "address": "94-071 Waipahu Depot Street, Waipahu, HI 96797",
        "lat": 21.388,
        "lng": -158.008,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 676-8878",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank", "yard-waste"]),
    },
    {
        "name": "ʻEwa Beach Convenience Center",
        "facility_type": "City convenience center — bulky / green waste / special waste",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96706",
        "address": "91-1000 Geiger Road, ʻEwa Beach, HI 96706",
        "lat": 21.318,
        "lng": -158.018,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 226-2996",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank", "yard-waste"]),
    },
    {
        "name": "Kapolei Convenience Center",
        "facility_type": "City convenience center — bulky / green waste / special waste",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96707",
        "address": "91-184 Kaomi Loop, Kapolei, HI 96707",
        "lat": 21.328,
        "lng": -158.088,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 260-2801",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank", "yard-waste"]),
    },
    {
        "name": "Lāʻie Convenience Center",
        "facility_type": "City convenience center — bulky / green waste / special waste",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96762",
        "address": "56-020 Kamehameha Highway, Lāʻie, HI 96762",
        "lat": 21.648,
        "lng": -157.918,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 293-8714",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank", "yard-waste"]),
    },
    {
        "name": "Wahiawā Convenience Center",
        "facility_type": "City convenience center — bulky / special waste (no green waste)",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96786",
        "address": "71-129 Wilikina Drive, Wahiawā, HI 96786",
        "lat": 21.488,
        "lng": -158.028,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Daily 7:00–18:00",
        "phone": "(808) 621-3648",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES, ["car-battery", "propane-tank"]),
    },
    {
        "name": "Waimānalo Gulch Sanitary Landfill",
        "facility_type": "Municipal landfill — inert / C&D / dead animals",
        "city_slug": "honolulu",
        "state": "HI",
        "zip": "96707",
        "address": "92-460 Farrington Highway, Kapolei, HI 96707",
        "lat": 21.308,
        "lng": -158.118,
        "source_url": "https://www.honolulu.gov/env/ref/waste-drop-off-locations/",
        "hours": "Mon–Sat 7:00–16:30",
        "phone": "(808) 668-2985",
        "accepted_materials": mats(["construction-debris", "concrete", "yard-waste"]),
    },
    # ── Louisville (louisvilleky.gov) ──
    {
        "name": "Southwest Government Center — staffed recycling",
        "facility_type": "Staffed recycling drop-off center",
        "city_slug": "louisville",
        "state": "KY",
        "zip": "40258",
        "address": "7219 Dixie Highway, Louisville, KY 40258",
        "lat": 38.138,
        "lng": -85.838,
        "source_url": "https://louisvilleky.gov/government/public-works/map-recycling-locations-louisville",
        "hours": "Tue–Sat 10:00–17:00",
        "phone": "502-574-3571",
        "accepted_materials": mats(RECYCLE, ["motor-oil", "antifreeze"]),
    },
    {
        "name": "Central Government Center — staffed recycling",
        "facility_type": "Staffed recycling drop-off center",
        "city_slug": "louisville",
        "state": "KY",
        "zip": "40219",
        "address": "7201 Outer Loop, Louisville, KY 40219",
        "lat": 38.138,
        "lng": -85.668,
        "source_url": "https://louisvilleky.gov/government/public-works/map-recycling-locations-louisville",
        "hours": "Tue–Sat 10:00–17:00",
        "phone": "502-574-3571",
        "accepted_materials": mats(RECYCLE, ["motor-oil", "antifreeze"]),
    },
    {
        "name": "East District Public Works — staffed recycling",
        "facility_type": "Staffed recycling drop-off center",
        "city_slug": "louisville",
        "state": "KY",
        "zip": "40207",
        "address": "595 N. Hubbards Lane, Louisville, KY 40207",
        "lat": 38.248,
        "lng": -85.648,
        "source_url": "https://louisvilleky.gov/government/public-works/map-recycling-locations-louisville",
        "hours": "Tue–Sat 10:00–17:00",
        "phone": "502-574-3571",
        "accepted_materials": mats(RECYCLE, ["motor-oil", "antifreeze"]),
    },
    *[
        {
            "name": f"Louisville unstaffed recycling — {label}",
            "facility_type": "Unstaffed recycling drop-off",
            "city_slug": "louisville",
            "state": "KY",
            "zip": z,
            "address": addr,
            "lat": lat,
            "lng": lng,
            "source_url": "https://louisvilleky.gov/government/public-works/map-recycling-locations-louisville",
            "hours": "24 hours (some fire stations 8:00–20:00)",
            "phone": "502-574-3571",
            "accepted_materials": mats(RECYCLE),
        }
        for label, addr, z, lat, lng in [
            ("Beechmont", "205 W. Wellington Avenue, Louisville, KY 40214", "40214", 38.168, -85.768),
            ("Fairdale", "10104 Mitchell Hill Road, Louisville, KY 40118", "40118", 38.148, -85.868),
            ("Fern Creek", "7700 Routt Road, Louisville, KY 40228", "40228", 38.148, -85.518),
            ("A.B. Sawyer Park", "9200 Whipps Mill Road, Louisville, KY 40222", "40222", 38.268, -85.618),
            ("Cyril Allgeier", "4101 Cadillac Court, Louisville, KY 40213", "40213", 38.188, -85.718),
            ("Bowman Field", "3501 Roger E. Schupp Street, Louisville, KY 40205", "40205", 38.228, -85.658),
            ("Lower River Road", "10450 Lower River Road, Jeffersonville, IN 47130", "47130", 38.328, -85.728),
            ("Aiken Road", "13312 Aiken Road, Louisville, KY 40245", "40245", 38.298, -85.478),
        ]
    ],
    # ── Durham County convenience centers (durhamnc.gov) ──
    *[
        {
            "name": f"Durham County Convenience Center — {label}",
            "facility_type": "County convenience center — trash / recycling",
            "city_slug": "durham",
            "state": "NC",
            "zip": z,
            "address": addr,
            "lat": lat,
            "lng": lng,
            "source_url": "https://www.durhamnc.gov/870/Recycling-Drop-Off-Sites",
            "hours": "Confirm on durhamnc.gov — county sticker may be required for city residents",
            "phone": phone,
            "accepted_materials": mats(BULKY, RECYCLE),
        }
        for label, addr, z, lat, lng, phone in [
            ("Bahama", "Quail Roost Road and Ball Road, Bahama, NC 27503", "27503", 36.118, -78.838, "919-477-8552"),
            ("Redwood", "Redwood Road and Electra Drive, Durham, NC 27704", "27704", 36.048, -78.868, "919-682-8200"),
            ("Rougemont", "U.S. 501 North and Bill Poole Road, Rougemont, NC 27572", "27572", 36.218, -78.938, "919-477-4325"),
        ]
    ],
    # ── Norfolk recycling drop-offs (norfolk.gov) ──
    {
        "name": "Waste Management Recycling Drop-Off — Pineridge Road",
        "facility_type": "24-hour curbside recycling drop-off",
        "city_slug": "norfolk",
        "state": "VA",
        "zip": "23502",
        "address": "1176 Pineridge Road, Norfolk, VA 23502",
        "lat": 36.858,
        "lng": -76.218,
        "source_url": "https://www.norfolk.gov/4813/Recycling-Information",
        "hours": "24 hours daily",
        "phone": "757-664-6510",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Towing and Recovery Recycling Drop-Off — Lance Road",
        "facility_type": "24-hour curbside recycling drop-off",
        "city_slug": "norfolk",
        "state": "VA",
        "zip": "23518",
        "address": "1188-A Lance Road, Norfolk, VA 23518",
        "lat": 36.898,
        "lng": -76.198,
        "source_url": "https://www.norfolk.gov/4813/Recycling-Information",
        "hours": "24 hours daily (e-waste not accepted — use SPSA Transfer Station)",
        "phone": "757-664-6510",
        "accepted_materials": mats(RECYCLE),
    },
    # ── Virginia Beach (pw.virginiabeach.gov) ──
    {
        "name": "West Neck Recycling Center",
        "facility_type": "Neighborhood recycling drop-off",
        "city_slug": "virginia-beach",
        "state": "VA",
        "zip": "23452",
        "address": "2500 West Neck Road, Virginia Beach, VA 23452",
        "lat": 36.867,
        "lng": -76.130,
        "source_url": "https://pw.virginiabeach.gov/trash-recycling/recycling-information",
        "hours": "Mon–Sat 7:00–16:30; trailers not permitted",
        "phone": "757-385-4650",
        "accepted_materials": mats(RECYCLE),
    },
    # ── Winston-Salem / Forsyth (forsyth.cc) ──
    {
        "name": "Forsyth County Recycling Center — Hanes Mill",
        "facility_type": "County recycling convenience center",
        "city_slug": "winston-salem",
        "state": "NC",
        "zip": "27105",
        "address": "325 West Hanes Mill Road, Winston-Salem, NC 27105",
        "lat": 36.145,
        "lng": -80.310,
        "source_url": "https://www.forsyth.cc/eap/recycling.aspx",
        "hours": "Mon–Fri 7:00–16:30; Sat 8:00–12:00",
        "phone": "336-703-2440",
        "accepted_materials": mats(RECYCLE, APPLIANCE),
    },
    {
        "name": "Forsyth County Recycling Center — Kernersville",
        "facility_type": "County recycling convenience center",
        "city_slug": "winston-salem",
        "state": "NC",
        "zip": "27284",
        "address": "445 Lindsay Street, Kernersville, NC 27284",
        "lat": 36.118,
        "lng": -80.068,
        "source_url": "https://www.forsyth.cc/eap/recycling.aspx",
        "hours": "Tue–Sat 8:00–17:00",
        "phone": "336-703-2440",
        "accepted_materials": mats(RECYCLE, APPLIANCE),
    },
    {
        "name": "Forsyth County Recycling Center — Pfafftown",
        "facility_type": "County recycling convenience center",
        "city_slug": "winston-salem",
        "state": "NC",
        "zip": "27040",
        "address": "6328 Yadkinville Road, Pfafftown, NC 27040",
        "lat": 36.158,
        "lng": -80.368,
        "source_url": "https://www.forsyth.cc/eap/recycling.aspx",
        "hours": "Tue–Sat 8:00–17:00",
        "phone": "336-703-2440",
        "accepted_materials": mats(RECYCLE, APPLIANCE),
    },
    # ── Greensboro / Guilford (guilfordcountync.gov) ──
    {
        "name": "White Street Landfill Recycling Drop-Off",
        "facility_type": "Landfill recycling drop-off — paper / metal / plastic / glass",
        "city_slug": "greensboro",
        "state": "NC",
        "zip": "27405",
        "address": "2503 White Street, Greensboro, NC 27405",
        "lat": 36.128,
        "lng": -79.748,
        "source_url": "https://www.guilfordcountync.gov/solid-waste-disposal-sites",
        "hours": "Mon–Fri 8:00–16:00",
        "phone": "336-641-3792",
        "accepted_materials": mats(RECYCLE),
    },
    {
        "name": "Guilford County Farm — e-waste drop-off",
        "facility_type": "County electronics recycling drop-off",
        "city_slug": "greensboro",
        "state": "NC",
        "zip": "27249",
        "address": "7315 Howerton Road, Gibsonville, NC 27249",
        "lat": 36.088,
        "lng": -79.648,
        "source_url": "https://www.guilfordcountync.gov/government/departments-and-agencies/planning-and-development/environmental-services/electronics-disposal",
        "hours": "Mon–Fri 8:00–16:00",
        "phone": "336-641-9431",
        "accepted_materials": mats(E_WASTE),
    },
    # ── Nashville drop-off recycling (nashville.gov) ──
    *[
        {
            "name": f"{label} — recycling drop-off",
            "facility_type": "Drop-off recycling site",
            "city_slug": "nashville",
            "state": "TN",
            "zip": z,
            "address": addr,
            "lat": lat,
            "lng": lng,
            "source_url": "https://www.nashville.gov/departments/waste-services/convenience-centers/hours-and-locations",
            "hours": hours,
            "phone": "(615) 862-5000",
            "accepted_materials": mats(RECYCLE),
        }
        for label, addr, z, lat, lng, hours in [
            ("WeGo Bellevue Park and Ride", "7650 Coley Davis Road, Nashville, TN 37221", "37221", 36.065, -86.935, "Daily 24 hours"),
            ("William Whitfield Park", "5150 Edmondson Pike, Nashville, TN 37211", "37211", 36.045, -86.725, "Sat 9:00–12:00"),
            ("Hillsboro High School", "3812 Hillsboro Pike, Nashville, TN 37215", "37215", 36.105, -86.815, "Daily 8:00–18:00 (closes 17:00 in winter)"),
            ("Joelton Middle School", "3500 Old Clarksville Pike, Joelton, TN 37080", "37080", 36.315, -86.875, "Daily 24 hours"),
            ("Lakewood City Hall", "3401 Old Hickory Boulevard, Old Hickory, TN 37138", "37138", 36.255, -86.645, "Daily 24 hours"),
            ("McGavock High School", "3150 McGavock Pike, Nashville, TN 37214", "37214", 36.185, -86.655, "Daily 24 hours"),
            ("Whites Creek High School", "7277 Old Hickory Boulevard, Whites Creek, TN 37189", "37189", 36.265, -86.825, "Daily 24 hours"),
        ]
    ],
    # ── Chattanooga (chattanooga.gov) ──
    {
        "name": "Chattanooga Recycle Center — Brainerd Road",
        "facility_type": "Municipal recycling drop-off",
        "city_slug": "chattanooga",
        "state": "TN",
        "zip": "37411",
        "address": "3924 Brainerd Road, Chattanooga, TN 37411",
        "lat": 35.018,
        "lng": -85.248,
        "source_url": "https://chattanooga.gov/services/waste-recycling",
        "hours": "Mon–Sat 8:00–17:00",
        "phone": "423-643-6311",
        "accepted_materials": mats(RECYCLE, E_WASTE),
    },
    {
        "name": "Chattanooga Refuse Collection Center — Airport Road",
        "facility_type": "Municipal refuse center — bulky / yard waste",
        "city_slug": "chattanooga",
        "state": "TN",
        "zip": "37421",
        "address": "4276 Airport Road, Chattanooga, TN 37421",
        "lat": 35.032,
        "lng": -85.202,
        "source_url": "https://chattanooga.gov/services/waste-recycling",
        "hours": "Mon–Sat 8:00–17:00",
        "phone": "423-643-6311",
        "accepted_materials": mats(BULKY, ["yard-waste"], TIRES),
    },
    # ── Grand Rapids / Kent County (kentcountymi.gov) ──
    {
        "name": "South Kent Recycling & Waste Center",
        "facility_type": "County landfill / self-haul drop-off",
        "city_slug": "grand-rapids",
        "state": "MI",
        "zip": "49315",
        "address": "10300 South Kent Drive, Byron Center, MI 49315",
        "lat": 42.812,
        "lng": -85.668,
        "source_url": "https://www.kentcountymi.gov/274/South-Kent-Recycling-Waste-Center",
        "hours": "Mon–Fri 7:30–16:30; Sat 7:30–12:00",
        "phone": "616-632-7920",
        "accepted_materials": mats(BULKY, APPLIANCE, TIRES),
    },
    {
        "name": "Kent County Waste-to-Energy Facility",
        "facility_type": "Waste-to-energy — municipal solid waste drop-off",
        "city_slug": "grand-rapids",
        "state": "MI",
        "zip": "49503",
        "address": "950 Market Avenue SW, Grand Rapids, MI 49503",
        "lat": 42.958,
        "lng": -85.678,
        "source_url": "https://www.kentcountymi.gov/683/Waste-to-Energy-Facility",
        "hours": "Mon–Fri 7:30–16:30",
        "phone": "616-632-7920",
        "accepted_materials": mats(BULKY),
    },
    # ── Richmond East Side (rva.gov) ──
    {
        "name": "East Richmond Road Convenience Center",
        "facility_type": "Convenience center — bulk / brush / tires",
        "city_slug": "richmond",
        "state": "VA",
        "zip": "23223",
        "address": "3800 East Richmond Road, Richmond, VA 23223",
        "lat": 37.555,
        "lng": -77.385,
        "source_url": "https://www.rva.gov/public-works/trash-collection",
        "hours": "Mon–Fri 7:00–15:30; Sat 8:30–14:00",
        "phone": "804-646-6434",
        "accepted_materials": mats(BULKY, TIRES, ["yard-waste"]),
    },
]


def main() -> None:
    for row in FACILITIES:
        row["accepted_materials"] = mats(row["accepted_materials"])

    facilities = json.loads(FAC_PATH.read_text())
    by_key = {(f.get("city_slug"), f.get("name")): i for i, f in enumerate(facilities)}
    added = updated = 0
    for row in FACILITIES:
        key = (row["city_slug"], row["name"])
        if key in by_key:
            facilities[by_key[key]] = {**facilities[by_key[key]], **row}
            updated += 1
        else:
            facilities.append(row)
            by_key[key] = len(facilities) - 1
            added += 1

    FAC_PATH.write_text(json.dumps(facilities, indent=2) + "\n")

    cities = [
        "atlanta", "charlotte", "raleigh", "durham", "greensboro", "winston-salem",
        "nashville", "memphis", "chattanooga", "louisville", "lexington", "richmond",
        "norfolk", "virginia-beach", "chesapeake", "new-orleans", "birmingham",
        "honolulu", "anchorage", "boise", "madison", "grand-rapids", "providence",
        "des-moines",
    ]
    total = sum(1 for f in facilities if f.get("city_slug") in cities)
    print(json.dumps({"added": added, "updated": updated, "metro_total": total}, indent=2))


if __name__ == "__main__":
    main()
